### ISSUE TITLE
How do I change the site title?

### ISSUE THREAD

**Issue by Goth** [chipzoller/hugo-clarity#10]
![Screenshot 2020-08-03 at 15 39 21](https://user-images.githubusercontent.com/1408367/89183413-e06d5780-d59f-11ea-8033-21526de49345.png)
I want to change the name of the theme to my website name? How?

Thansks.

**Comment by onweru** [comment]
@Goth, [edit this line in the config](https://github.com/chipzoller/hugo-clarity/blob/0cbe3367c3a136dfe65f3ecc110a3c2db4775cba/exampleSite/config.toml#L4). If you have a different configuration, that would be the `title` field in your _config.toml_ file
