### ISSUE TITLE
Problem displaying more than 14 tags on sidebar.

### ISSUE THREAD

**Issue by manuxch** [chipzoller/hugo-clarity#101]
**I have checked all the prerequisites below and I'm yet experiencing a problem**

- [X] Read the README.md
- [X] Have the extended version of Hugo installed
- [X] Used the exampleSite's config.toml as a reference

**Describe the bug**

The site is not built when I add a new post increasing the number of tags to 15. In the config.toml file, the parameter "numberOfTagsShown" is set to 14. The error I got in the browser (and also in console) is::

> render of "page" failed: execute of template failed: template: _default/single.html:28:6: executing "main" at <partial "sidebar" .>: error calling partial: "/tmp/hugo_cache/modules/filecache/modules/pkg/mod/github.com/chipzoller/hugo-clarity@v0.0.0-20201205203449-1d5401c587bc/layouts/partials/sidebar.html:46:69": execute of template failed: template: partials/sidebar.html:46:69: executing "partials/sidebar.html" at <T>: wrong number of args for T: want at least 1 got 0
> render of "page" failed: execute of template failed: template: _default/single.html:28:6: executing "main" at <partial "sidebar" .>: error calling partial: "/tmp/hugo_cache/modules/filecache/modules/pkg/mod/github.com/chipzoller/hugo-clarity@v0.0.0-20201205203449-1d5401c587bc/layouts/partials/sidebar.html:46:69": execute of template failed: template: partials/sidebar.html:46:69: executing "partials/sidebar.html" at <T>: wrong number of args for T: want at least 1 got 0
> render of "page" failed: execute of template failed: template: _default/single.html:28:6: executing "main" at <partial "sidebar" .>: error calling partial: "/tmp/hugo_cache/modules/filecache/modules/pkg/mod/github.com/chipzoller/hugo-clarity@v0.0.0-20201205203449-1d5401c587bc/layouts/partials/sidebar.html:46:69": execute of template failed: template: partials/sidebar.html:46:69: executing "partials/sidebar.html" at <T>: wrong number of args for T: want at least 1 got 0
> render of "page" failed: execute of template failed: template: _default/single.html:28:6: executing "main" at <partial "sidebar" .>: error calling partial: "/tmp/hugo_cache/modules/filecache/modules/pkg/mod/github.com/chipzoller/hugo-clarity@v0.0.0-20201205203449-1d5401c587bc/layouts/partials/sidebar.html:46:69": execute of template failed: template: partials/sidebar.html:46:69: executing "partials/sidebar.html" at <T>: wrong number of args for T: want at least 1 got 0
> Rebuild failed:
> 
> Failed to render pages: render of "page" failed: execute of template failed: template: _default/single.html:28:6: executing "main" at <partial "sidebar" .>: error calling partial: "/tmp/hugo_cache/modules/filecache/modules/pkg/mod/github.com/chipzoller/hugo-clarity@v0.0.0-20201205203449-1d5401c587bc/layouts/partials/sidebar.html:46:69": execute of template failed: template: partials/sidebar.html:46:69: executing "partials/sidebar.html" at <T>: wrong number of args for T: want at least 1 got 0
> 
> Hugo Static Site Generator v0.78.2/extended linux/amd64 BuildDate: 2020-11-16T11:43:13Z

I installed the Clarity theme using the Option 3, and I simply add some new posts in /content/post/ of the exampleSite. I would really appreciate if you can tell me how can I fix this, because the Clarity theme is beatiful and I'm very happy with it.

**Desktop (please complete the following information):**
 - OS: Debian testing
 - Browser: Firefox 83.0 (64 bit)

**Comment by onweru** [comment]
@manuxch, I will try to reproduce this and get back to you

**Comment by rahulwagh** [comment]
+1 @manuxch 

I am also using the hugo clarity for some time now but recent update has broken the ```hugo server``` command

and now i am also stuck with 

```
Start building sites … 
ERROR 2020/12/08 14:00:34 render of "page" failed: execute of template failed: template: _default/single.html:28:6: executing "main" at <partial "sidebar" .>: error calling partial: "/Users/rwagh/Jhooq/jhooq/themes/hugo-clarity/layouts/partials/sidebar.html:46:69": execute of template failed: template: partials/sidebar.html:46:69: executing "partials/sidebar.html" at <T>: wrong number of args for T: want at least 1 got 0
ERROR 2020/12/08 14:00:34 render of "page" failed: execute of template failed: template: _default/single.html:28:6: executing "main" at <partial "sidebar" .>: error calling partial: "/Users/rwagh/Jhooq/jhooq/themes/hugo-clarity/layouts/partials/sidebar.html:46:69": execute of template failed: template: partials/sidebar.html:46:69: executing "partials/sidebar.html" at <T>: wrong number of args for T: want at least 1 got 0
ERROR 2020/12/08 14:00:34 render of "page" failed: execute of template failed: template: _default/single.html:28:6: executing "main" at <partial "sidebar" .>: error calling partial: "/Users/rwagh/Jhooq/jhooq/themes/hugo-clarity/layouts/partials/sidebar.html:46:69": execute of template failed: template: partials/sidebar.html:46:69: executing "partials/sidebar.html" at <T>: wrong number of args for T: want at least 1 got 0
ERROR 2020/12/08 14:00:34 render of "page" failed: execute of template failed: template: _default/single.html:28:6: executing "main" at <partial "sidebar" .>: error calling partial: "/Users/rwagh/Jhooq/jhooq/themes/hugo-clarity/layouts/partials/sidebar.html:46:69": execute of template failed: template: partials/sidebar.html:46:69: executing "partials/sidebar.html" at <T>: wrong number of args for T: want at least 1 got 0
Built in 1230 ms
Error: Error building site: failed to render pages: render of "page" failed: execute of template failed: template: _default/single.html:28:6: executing "main" at <partial "sidebar" .>: error calling partial: "/Users/rwagh/Jhooq/jhooq/themes/hugo-clarity/layouts/partials/sidebar.html:46:69": execute of template failed: template: partials/sidebar.html:46:69: executing "partials/sidebar.html" at <T>: wrong number of args for T: want at least 1 got 0
```

Any update help would be really appreciated because i need to update my blog but somehow i got stuck after this recent update .

//Rahul

**Comment by onweru** [comment]
@rahulwagh, @manuxch 

I couldn't quite reproduce the error I fixed something that seemed off to me. Let me know if this update fixes things for you

**Comment by rahulwagh** [comment]
@onweru your fix did the trick for me and now the theme is working thanks!
