### ISSUE TITLE
Feature Request: Add archive page and support more comment system

### ISSUE THREAD

**Issue by Y4er** [chipzoller/hugo-clarity#107]
# Add archive page
There are too many articles. It is troublesome to turn page by page. I hope there is a page to store the article archive.

like this: https://themes.gohugo.io//theme/hugo-theme-zzo/en/archive

# support more comment system
in china,Access to Disqus is very slow, a better option is utteranc.

If I have time, I will submit pr to do these things. thanks.

**Comment by chipzoller** [comment]
Supporting Utterances is something we have considered. A PR that adds this would be most welcome.

**Comment by onweru** [comment]
Agree, something like https://github.com/chipzoller/hugo-clarity/pull/83 but documented in the readme.
