### ISSUE TITLE
Help wanted: Show my own favicon

### ISSUE THREAD

**Issue by bluelupo** [chipzoller/hugo-clarity#108]
Hello,
I would like to change the favicon in the Clarity theme to a custom icon. Which configuration files do I have to change for this and which graphic files (png) do I have to replace. 

I found a configuration file (favicon.html), but changes in the file $HOME/hugo/layouts/partials/favicon.html have no effect on the displayed favicon.ico.

Listing of the unchanged favicon.html:

> \<link rel='apple-touch-icon' sizes='180x180' href='{{ absURL "icons/apple-touch-icon.png" }}'>
> \<link rel='icon' type='image/png' sizes='32x32' href='{{ absURL "icons/favicon-32x32.png" }}'>
> \<link rel='icon' type='image/png' sizes='16x16' href='{{ absURL "icons/favicon-16x16.png" }}'>
> \<link rel='manifest' href='{{ absURL "icons/site.webmanifest" }}'>
> \<link rel="mask-icon" href= '{{ absURL "safari-pinned-tab.svg" }}' color="#002538">
> \<meta name="msapplication-TileColor" content="#002538">
> \<meta name="theme-color" content="#002538">

Is this even the right place where I can change the display of the favicon? I would be glad if you could help me.

regards
Michael

**Comment by onweru** [comment]
@bluelupo, add your favicons inside `static/icons` directory

**Comment by Simon99de** [comment]
> @bluelupo, add your favicons inside `static/icons` directory. Use [this tool](https://realfavicongenerator.net) to generate your favicon files

Please add this to the instructions :) The favicon is still missing.
