### ISSUE TITLE
Links menu (data/menu,yaml) template is missing, 404 in docs

### ISSUE THREAD

**Issue by aliddell** [chipzoller/hugo-clarity#111]
**I have checked all the prerequisites below and I'm yet experiencing a problem**

- [x] Read the README.md
- [x] Have the extended version of Hugo installed
- [x] Used the exampleSite's config.toml as a reference

**Describe the bug**

The link under "edit this YAML file" in the docs [here](https://themes.gohugo.io/hugo-clarity/#modify-links-menu) (and consequently in the [readme](https://github.com/chipzoller/hugo-clarity#modify-links-menu)) is dead (404 response).

**Comment by onweru** [comment]
True that info is dated. Updating now. Use the config.toml file instead
