### ISSUE TITLE
Question: showing Related Content

### ISSUE THREAD

**Issue by hiensarahly** [chipzoller/hugo-clarity#112]
Hey Clarity theme Creators! 

Is the “Articles in the Exploring Kyverno series” part here manually added, on every post in the series?

https://neonmirrors.net/post/2020-12/exploring-kyverno-part3/#articles-in-the-exploring-kyverno-series

Can it be configured to show Related Content with the same Tags or Categories?

**Comment by chipzoller** [comment]
Yes, that was added manually. Currently theme can't do what you're asking in an automated fashion. It's worth considering, however that's kinda the whole purpose of using tags and categories to begin with: so users can find related content if they wish. Having all content with the same tag(s) and/or categories seems a bit superfluous, I suppose.

**Comment by hiensarahly** [comment]
Ah, forgot about that! I just tried it on mobile—the sidebar part becomes the bottom part of the post. That’ll work then.🙂 And yes, sometimes to use/customize a theme, it’s good first to understand the theme makers intentions.

**Comment by hiensarahly** [comment]
On desktops and tablets, when one finishes reading a post they’ll have to scroll back up to find similar tags.

**Comment by chipzoller** [comment]
>On desktops and tablets, when one finishes reading a post they’ll have to scroll back up to find similar tags.
Yes, that's how it works.

**Comment by hiensarahly** [comment]
It’s a common feature for the flow of the user’s reading experience. Just sharing some feedback. Was not criticizing. Seems like you’re not open for this so I’ll be closing it.
