### ISSUE TITLE
Custom home page

### ISSUE THREAD

**Issue by hiensarahly** [chipzoller/hugo-clarity#113]
Thanks guys for making this theme! Is there an option for making a custom home page, or other custom pages?

**Comment by chipzoller** [comment]
When you're talking about "custom" pages, this is somewhat outside the scope of a theme to begin with (the theme provides "cookie cutter" pages with similar aesthetics), but you're welcome to create any page you want as standard HTML. If you maybe meant something else by "custom" please clarify.

**Comment by hiensarahly** [comment]
I mean if we can configure a home page, for example, as a brief introduction to the site. Then have all the blog posts moved over to a Blog section—with Blog on the top menu. Is it doable from your experience?

**Comment by chipzoller** [comment]
Anything is doable, but it's not something we provide for in this theme.
