### ISSUE TITLE
Question: Clarity theme customization

### ISSUE THREAD

**Issue by hiensarahly** [chipzoller/hugo-clarity#114]
If we git clone the Clarity theme to our local repo, make some changes, push it to a different remote repository... then, whenever the original Clarity theme here gets updates, will doing git pull to the local repo override the theme customizations?

**Comment by chipzoller** [comment]
You would fork this repo first, then `git clone` locally. From that point forward, any changes to this repo will not automatically be reflected in your forked copy. You can choose to rebase or merge the upstream with your fork, but you may have merge conflicts.

**Comment by hiensarahly** [comment]
Thanks
