### ISSUE TITLE
thumbnail 404 not found in tag page

### ISSUE THREAD

**Issue by LGTMXD** [chipzoller/hugo-clarity#13]
![image](https://user-images.githubusercontent.com/30213081/89375212-ceb2be00-d71f-11ea-9537-796ecc052155.png)

![image](https://user-images.githubusercontent.com/30213081/89374944-3c121f00-d71f-11ea-90be-b228411a55e4.png)

![image](https://user-images.githubusercontent.com/30213081/89375056-74196200-d71f-11ea-8a83-4a644e9c294f.png)

**Comment by onweru** [comment]
thanks for contributing @LGTMXD
