### ISSUE TITLE
Feature: Add configuration parameter to disable theme switch

### ISSUE THREAD

**Issue by Monklite** [chipzoller/hugo-clarity#131]
I think that the day/night toggle switch is pretty cool; however, my website is intended to be themed dark consistently and I'd prefer to remove the day/night toggle. I could just pull it out of the code, but a configuration parameter to disable it would be a better solution as it would provide that option to everybody.

**Comment by onweru** [comment]
Interesting, I have always thought that the user must always reserve the right to choose, https://github.com/chipzoller/hugo-clarity#forcing-light-or-dark-mode. That’s whenever possible, I as a site owner should not have to unilaterally decide what’s best for them. 

![700767C8-7688-420C-811B-722C537CD03A](https://user-images.githubusercontent.com/16350351/106356414-7516ff00-6310-11eb-80a7-7f5ceb4066be.jpeg)

**Comment by chipzoller** [comment]
I think the danger we have with things like this (not singling anyone out) is that we risk creating **too many** knobs and switches for params. Making the theme extensible and customizable was a goal, but a non-goal was to effectively enable a "build-your-own" by tweaking parameters. We'll consider something like this, but no promises :)

**Comment by onweru** [comment]
This is definitely a [could have](https://en.wikipedia.org/wiki/MoSCoW_method#could) feature #MoSCoW

**Comment by Monklite** [comment]
> I think the danger we have with things like this (not singling anyone out) is that we risk creating **too many** knobs and switches for params. Making the theme extensible and customizable was a goal, but a non-goal was to effectively enable a "build-your-own" by tweaking parameters. We'll consider something like this, but no promises :)

I won't be offended if you choose to reject this idea, your reasoning is entirely understandable. Removing that part of the theme isn't difficult anyways, I can just comment it out. Think about it some more, but yes scope creep can be a real issue and it can quickly become overly complicated if not careful.
