### ISSUE TITLE
Internet Explorer requires compatibility

### ISSUE THREAD

**Issue by outbegin** [chipzoller/hugo-clarity#136]
This is a cool body but the layout displayed in Internet Explorer is cluttered.
Expect to improve！

 - Browser [Internet Explorer 18363.13.16]

**Comment by chipzoller** [comment]
Internet Explorer is a horrendous browser that is on its last leg. We built this theme optimized for modern browsers and not legacy technology. If you'd like to fork this theme and add support for IE, you're most welcome to do so, but we will not be working on this issue.
