### ISSUE TITLE
hugo version?

### ISSUE THREAD

**Issue by Goth** [chipzoller/hugo-clarity#14]
ERROR 2020/08/05 11:53:04 HUGO-CLARITY theme does not support Hugo version 0.54.0. Minimum version required is 0.63.0 
But i already have the latest version : hugo 0.74.3 already installed 

I can't upload from github to netlify because of this error.

**Comment by onweru** [comment]
@Goth, see instructions on setting up netlify deployment here https://gohugo.io/hosting-and-deployment/hosting-on-netlify/#configure-hugo-version-in-netlify. Netlify uses a different version of Hugo than the one you have installed locally.
