### ISSUE TITLE
Disqus Comments

### ISSUE THREAD

**Issue by olegtech** [chipzoller/hugo-clarity#140]
**I have checked all the prerequisites below and I'm yet experiencing a problem**

- [x] Read the README.md
- [x] Have the extended version of Hugo installed
- [x] Used the exampleSite's config.toml as a reference

**Describe the bug**
Thank you for the theme. I recently installed it but can't see any comment affect (disqus). 
- added to config.toml :  ***disqusShortname = "discuss_xxxxxx"***
- and to post page:  ***comment: true***

although it works fine thru ***layouts/partials/comments.html***

**Desktop :**
 - OS: [Ubuntu 20.04.2]
 - Browser [Firefox 85.0.1]
 - Hugo [v0.80.0/extended]

**Comment by onweru** [comment]
@olegtech, 

Please ensure that you follow these instructions carefully. 
https://gohugo.io/content-management/comments/#configure-disqus
https://github.com/chipzoller/hugo-clarity#comments
