### ISSUE TITLE
hugo build failed: can't evaluate field Title in type string

### ISSUE THREAD

**Issue by luizyao** [chipzoller/hugo-clarity#141]
**I have checked all the prerequisites below and I'm yet experiencing a problem**

- [x] Read the README.md
- [x] Have the extended version of Hugo installed
- [ ] Used the exampleSite's config.toml as a reference

**Describe the bug**

```bash
❯ hugo
ERROR 2021/02/15 09:17:40 render of "page" failed: "themes/hugo-clarity/layouts/_default/single.html:16:54": execute of template failed: template: _default/single.html:16:54: executing "main" at <.Title>: can't evaluate field Title in type string
```

It seem that there are problem to accessing page variables inside with function.

```html
{{ with .Params.featureImage }}
    <img src="{{ . }}" class="image_featured" alt="{{ .Title }}">
{{ end }}
```

**Desktop (please complete the following information):**
 - hugo version: v0.79.1/extended

**Comment by onweru** [comment]
Thanks @luizyao for reporting this. It should be fixed now.

**Comment by timschps** [comment]
have it too! I switched back to commit  88f6cf4
