### ISSUE TITLE
Include unnecessary strings in articles"true"

### ISSUE THREAD

**Issue by mochi5o** [chipzoller/hugo-clarity#145]
**I have checked all the prerequisites below and I'm yet experiencing a problem**

- [x] Read the README.md
- [x] Have the extended version of Hugo installed
- [x] Used the exampleSite's config.toml as a reference

**Describe the bug**

[https://themes.gohugo.io//theme/hugo-clarity/post/markdown-syntax/](https://themes.gohugo.io//theme/hugo-clarity/post/markdown-syntax/)
![image](https://user-images.githubusercontent.com/41158022/108857080-0aff2a80-762e-11eb-9987-75a03c9dfe04.png)

Hello. I'm a beginner. This is my first time using hugo.
After the change on Feb 20th, the string "true" seems to appear at the bottom of articles.
Could you please check?
I solved the problem by removing the following part.

https://github.com/chipzoller/hugo-clarity/blob/master/layouts/_default/single.html#L26-L35

**Desktop (please complete the following information):**
 - OS: [MacOS 10.15.7]
 - Browser [chrome:88.0  , Firefox: 72.0.1]

**Comment by mochi5o** [comment]
And thank you for making such a cool theme. I would love to keep using this!!

**Comment by onweru** [comment]
@mochi5o, thank you for catching this. Fixing right away
