### ISSUE TITLE
Fails to load in live and multiple errors shows up in console

### ISSUE THREAD

**Issue by gainngo** [chipzoller/hugo-clarity#148]
**I have checked all the prerequisites below and I'm yet experiencing a problem**

- [✅ ] Read the README.md
- [✅ ] Have the extended version of Hugo installed
- [✅] Used the exampleSite's config.toml as a reference

**Describe the bug**
1. Unable to get the site details like title and desc updated (despite having the details updated in config file)
![image](https://user-images.githubusercontent.com/79978087/109854627-45e00e80-7c7d-11eb-8646-9b9531eecb06.png)

![image](https://user-images.githubusercontent.com/79978087/109854696-5abca200-7c7d-11eb-8e92-10ae8788242f.png)

2. The site fails to load after deploying - lot of errors related to css / integrity issues

![image](https://user-images.githubusercontent.com/79978087/109854396-031e3680-7c7d-11eb-8a7e-1dae82fe490a.png)

![image](https://user-images.githubusercontent.com/79978087/109854956-b0914a00-7c7d-11eb-8077-71a96018650d.png)

3. The mobile menu looks messed up:
![image](https://user-images.githubusercontent.com/79978087/109854513-221cc880-7c7d-11eb-8c32-90aa719d65e7.png)

repo link: https://github.com/gainngo/blog

**Desktop (please complete the following information):**
 - OS: [e.g. iOS 14, Windows 10] - windows 10
 - Browser [e.g. chrome 76, safari 13] - chrome & firefox

Kindly let me know if I'm missing anything here.

**Comment by onweru** [comment]
@gainngo, could you try setting your baseURL as `https://www.gainngo.com/`?

**Comment by gainngo** [comment]
@onweru I remember setting the baseURL to the same. However, I have installed another theme. So I guess this issue is not longer relevant :(
