### ISSUE TITLE
code block doesnt show all lines after clicking expansion button

### ISSUE THREAD

**Issue by LGTMXD** [chipzoller/hugo-clarity#15]
![image](https://user-images.githubusercontent.com/30213081/89701302-0c098c80-d968-11ea-8c58-9ee8a9885ec2.png)

![image](https://user-images.githubusercontent.com/30213081/89701304-0f9d1380-d968-11ea-8a8a-bb3a0b2429c6.png)

**Comment by onweru** [comment]
@LGTMXD, thanks a lot for highlighting this using dev tools. We have been aware of this bug but couldn't quite place a finger on what was causing it. Thanks for contributing.
