### ISSUE TITLE
How should I practically change the font to use system default font?  (because bold doesn't take effect)

### ISSUE THREAD

**Issue by mc-gulu** [chipzoller/hugo-clarity#150]
(For Chinese text, the bold doesn't work and it stills shows plain unbolded text)

I found that only `customFonts = true`  is related and I don't know how to proceed to change the font.

The markdown source:

![001](https://user-images.githubusercontent.com/1855937/110716348-f16efd00-8241-11eb-849e-9e0b2001f221.png)

The rendered effect:

![002](https://user-images.githubusercontent.com/1855937/110716350-f3d15700-8241-11eb-8933-90a72cc969d6.png)

**Comment by onweru** [comment]
@mc-gulu, thanks for raising this. I will apply a remedy asap

**Comment by rootwork** [comment]
I think it's just because [the fonts being loaded](https://github.com/chipzoller/hugo-clarity/blob/master/assets/sass/_fonts.sass) don't include a true "bold" version.

**Comment by mc-gulu** [comment]
> 
> 
> I think it's just because [the fonts being loaded](https://github.com/chipzoller/hugo-clarity/blob/master/assets/sass/_fonts.sass) don't include a true "bold" version.

Alright. 

I changed the font-face to 'Microsoft Yahei' but nothing changed and it still doesn;t show bold correctly.

![image_001](https://user-images.githubusercontent.com/1855937/112068346-ac818980-8ba4-11eb-88a1-4a4549023e09.png)

I removed the content of the `_font.sass` entirely to try to "clear the font customization" but nothing changes.

I'm not quite familiar with css. May I ask that how should I practically change the font used (like originally asked in the issue title) please?

**Comment by mc-gulu** [comment]
I also tried to change font in `_variables.sass` and `main.sass` but it doesn't work either.

**Comment by onweru** [comment]
@mc-gulu, please let me know if the change worked.

**Comment by mc-gulu** [comment]
It works!

![665C36E9-FDEF-478C-8CE1-FEF979425B9B](https://user-images.githubusercontent.com/1855937/112927733-0a374800-9148-11eb-9dee-dd172e126079.jpg)

**Comment by 1nformation** [comment]
怎么更改默认字体，大佬。
