### ISSUE TITLE
[BUG] Regression, image captions appear in featureImage

### ISSUE THREAD

**Issue by chipzoller** [chipzoller/hugo-clarity#151]
Hi all,

there was a change that added the Title as the alt text to the featureImage - that is very useful and seems to be seo relevant. But now the Title shows up under the first picture of an article as well - is there any way to disable this?

Thanks a lot

Thomas

_Originally posted by @konsumschaf in https://github.com/chipzoller/hugo-clarity/discussions/149_

**Comment by chipzoller** [comment]
@onweru Confirmed as a regression. Image referenced in `featureImage` should not display caption.

**Comment by onweru** [comment]
I will look into this
