### ISSUE TITLE
Feature request: Move all head declarations into `head.html` partial, or create multiple head partials

### ISSUE THREAD

**Issue by rootwork** [chipzoller/hugo-clarity#160]
I wanted to preload my self-hosted font, so I looked in the [`head.html` partial](https://github.com/chipzoller/hugo-clarity/blob/master/layouts/partials/head.html).

Turns out that's really only part of the HTML `<head>` section, though. The rest of it is defined in [`baseof.html`](https://github.com/chipzoller/hugo-clarity/blob/master/layouts/_default/baseof.html).

It would be nice to be able to override the head elements without having to maintain an override of the entire `baseof.html` document. So my suggestion would be to either:

1. move the styles definitions, scripts definitions, preloads, and styles file from `baseof.html` into `head.html`.
2. move each of those into their own partials (e.g. `head-styles`, `head-scripts`, etc.) and rename `head` to match what's currently in there. The `opengraph` and `favicon` partials that are currently getting called from `head` could move to being called directly from `baseof.html`.

Thanks for considering the suggestion.

**Comment by onweru** [comment]
@rootwork,

I define them all in the base because I wanted to preload the scripts as well. I wanted to define the variables in one place (DRY). In retrospect, I guess  I can use Hugo's [returning partial feature](https://gohugo.io/templates/partials/#returning-a-value-from-a-partial) to implement your request.

**Comment by rootwork** [comment]
Ah, that does make sense.

Well it's up to you of course, it's just an idea I had.

**Comment by chipzoller** [comment]
@onweru and @rootwork what should we do about this issue? Is there an outstanding action item here or has it been implemented?

**Comment by rootwork** [comment]
It hasn't been implemented. It's still something I'd like to see, if you're open to me putting up a PR for it.

**Comment by chipzoller** [comment]
So sorry for the delay, @rootwork ! @onweru what do you think? I'm fine with this.

**Comment by onweru** [comment]
@chipzoller, the declarations can be moved, it will still work.

**Comment by onweru** [comment]
@rootwork, I'm now working on this.

**Comment by rootwork** [comment]
I think we can close this now, unless @onweru you had plans to do something more in the future.

**Comment by onweru** [comment]
Absolutely 🤝, I will leave it as-is for now.
