### ISSUE TITLE
Menu and night mode switch do not work when cookies are disabled

### ISSUE THREAD

**Issue by atticoder** [chipzoller/hugo-clarity#169]
Menu and night mode switch do not work when cookies are disabled in the browser. 

When page is loaded on small screen so main menu is automatically hidden to be displayed by menu button, menu cannot be opened at all and thus site cannot be navigated.

**Comment by onweru** [comment]
@atticoder, that's by design. That switch uses a token that is saved to [the browser's localStorage](https://developer.mozilla.org/en-US/docs/Web/API/Window/localStorage)
