### ISSUE TITLE
Excess whitespace below except

### ISSUE THREAD

**Issue by atticoder** [chipzoller/hugo-clarity#171]
Excepts display excess whitespace between post meta items and actual excerpt text. Actual post page does not show such wide whitespace and is more pleasing to the eye. Seems the issue could be solved by reducing bottom margin of excerpt_header CSS class.

![excerpt_header height](https://user-images.githubusercontent.com/47108804/115696093-04114180-a36b-11eb-93bf-1bc67e7a9e21.png)

**Comment by onweru** [comment]
Consider opening a PR with improved spacing. In the PR, also include a screenshot of the improved version. I will consider it
