### ISSUE TITLE
If relativeURLs = true then loadSvg may fail to load 'icons/link.svg' and may crash page

### ISSUE THREAD

**Issue by atticoder** [chipzoller/hugo-clarity#176]
The image `link.svg` mentioned below is used on pages that have headings in text to display link image next to heading (when user hovers over the heading with the mouse).

This issue only happens with the following site config and **when site is deployed to a non-root folder (e.g. yourdomain.com/test)**:

```
relativeURLs = true
baseURL = "/"
```
Bundled JavaScript function:
```
const iconsPath = 'icons/';
function loadSvg(a, b, c=iconsPath) {
    const d = `${parentURL}${c}${a}.svg`;
    fetch(d).then(a=>a.text()).then(a=>{
        b.innerHTML = a
    }
    )
}
```
This function constructs file path `/icons/link.svg` which does not exist when site is deployed to /test subfolder of root (expected file path is `/test/icons/link.svg`). As the script seems not to have any error handling, **a page that tries to use `link.svg` will not display properly in Firefox (Windows)**, only partial page may be loaded or with missing style sheets. Chrome and Edge will handle better and the page will be painted completely, just the link images are missing.

Perhaps it is possible to move the `link.svg` as inline symbol into `partials/icons.html`?

**Comment by onweru** [comment]
@atticoder, thank you. This makes sense, I will apply a fix asap.
