### ISSUE TITLE
Featured posts parameter ignored

### ISSUE THREAD

**Issue by flyingdan** [chipzoller/hugo-clarity#18]
The front matter of the post archetype has a parameter named "featured" described as follows:

`featured: false # Sets if post is a featured post, making appear on the home page side bar.`

Setting this parameter to `true` does not cause the post to appear in the side bar. To make the post appear in the "Featured Posts" section of the sidebar a tag with name `featured` is required.

I believe this is because in the sidebar.html the code is looking at tags instead of parameters for creating the list of featured posts:
```html
<h2 class="mt-4">Featured Posts</h2>
<ul>
{{ range .Site.Taxonomies.tags.featured }}
 {{- if ne $title .Title }}
  <li>
    <a href="{{ .Permalink }}" class="nav-link">{{ .Title }}</a>
  </li>
{{- end }}
{{ end }}
</ul>
```

Note that even with the `featured` parameter set to false, if the tag exists the post is show in the side bar.

**Comment by chipzoller** [comment]
Thanks for mentioning this. We are aware of it and were going to remediate. @onweru I think it makes sense to accelerate this fix to ensure the README remains accurate.
