### ISSUE TITLE
Currently viewed post is filtered out of recent and featured lists

### ISSUE THREAD

**Issue by incenger** [chipzoller/hugo-clarity#19]
When a post in recent and featured list is viewed, it is filtered out of the recent and featured list. I think it would make more sense to keep these two lists consistent.
Thank you for your great work.

**Comment by chipzoller** [comment]
Thank you for pointing this out, and I agree. We will ensure the "Featured Posts" and "Recent Posts" lists on the side bar are consistent regardless of the current page being viewed.

**Comment by onweru** [comment]
This behaviour is a feature and not a bug; I [recently documented](https://github.com/chipzoller/hugo-clarity/commit/cccc1783e47653469be88381abb36c84aa5e4dc9) this [here](https://github.com/chipzoller/hugo-clarity/commit/cccc1783e47653469be88381abb36c84aa5e4dc9). Since the article is being read (open/in focus) anyway, it would seem redundant listing it as featured. Assuming the only reason you would like to tag an article as featured is to draw attention to it.

**Comment by RobJohnston** [comment]
For consideration, set the `active` attribute and add some style to indicate which is the current page.

Similar to the example of the Clarity Sidenav component:  https://clarity.design/documentation/sidenav

**Comment by oskapt** [comment]
> This behaviour is a feature and not a bug; I [recently documented](https://github.com/chipzoller/hugo-clarity/commit/cccc1783e47653469be88381abb36c84aa5e4dc9) this [here](https://github.com/chipzoller/hugo-clarity/commit/cccc1783e47653469be88381abb36c84aa5e4dc9). Since the article is being read (open/in focus) anyway, it would seem redundant listing it as featured. Assuming the only reason you would like to tag an article as featured is to draw attention to it.

There's an argument that UI elements shouldn't appear and disappear in arbitrary context. The article is Featured 100% of the time. The heading doesn't say "Featured and Not Visible" - so when it disappears, it's easy for the reader to attribute that to a state change around "Featured" and not a state change around "Not Visible."

**Comment by onweru** [comment]
> The article is Featured 100% of the time. 

If there's only one unit of a product,  you wouldn't re-advertise (feature)  it to the guy who just bought it.

> So when it disappears, it's easy for the reader to attribute that to a state change around "Featured" and not a state change around "Not Visible."

This falls under the realm of "trivia".

I think there's a case to be made that if an article is already being read, it should give up room for other featured articles to be noticed as well.
