### ISSUE TITLE
codeMaxLines and codeLineNumbers doesn't work as expected

### ISSUE THREAD

**Issue by jonlimx** [chipzoller/hugo-clarity#191]
**I have checked all the prerequisites below and I'm yet experiencing a problem**

- [x] Read the README.md
- [x] Have the extended version of Hugo installed
- [x] Used the exampleSite's config.toml as a reference

**Describe the bug**
codeMaxLines and codeLineNumbers doesn't work as expected. I set codeMaxLines = 10
and codeLineNumbers = true in params.toml (in config.toml).
![image](https://user-images.githubusercontent.com/9720225/124416659-1146a580-dd8a-11eb-92d8-2a1ca9f14b1a.png)

I didn't see line numbers, instead, I see a vertical blue bar on the left. And I didn't see the code expansion button. Please see the screenshot below.

![image](https://user-images.githubusercontent.com/9720225/124416541-d0e72780-dd89-11eb-9bc6-eae1dabdc3cb.png)

**Desktop (please complete the following information):**
 - OS: macOS big sur
 - Browser Microsoft Edge / Safari

**Comment by onweru** [comment]
@jonlimx, would you mind if I saw your entire setup i.e the repo?

**Comment by jonlimx** [comment]
@onweru Thanks for your time. Sure, I have config.toml, menus.zh.toml and params.toml under xxx/config/_default. I am pasting the configurations as follows:

**config.toml**
`baseURL = "https://www.jonathanlin.top/"
languageCode = "zh-cn"
title = "Standing on the Shoulder of Giants"
theme = "hugo-clarity"
DefaultContentLanguage = "zh"
copyright = "Copyright © {year} Jonathan Lin. All rights reserved."`

**params.toml**
`numberOfTagsShown = 14 # Applies for all other default & custom taxonomies. e.g categories, brands see https://gohugo.io/content-management/taxonomies#what-is-a-taxonomy
codeMaxLines = 10
codeLineNumbers = true`

**menus.zh.toml**
`[[main]]
  name = "Home"
  url = ""
  weight = -110

[[main]]
  name = "Archives"
  url = "post/rich-content/"
  weight = -109

# Submenus are done this way: parent -> identifier
[[main]]
  name = "Links"
  identifier = "Links"
  weight = -108
[[main]]
  parent = "Links"
  name = "LinkedIn"
  url = "https://www.linkedin.com/"
[[main]]
  parent = "Links"
  name = "Twitter"
  url = "https://twitter.com/"

[[main]]
  name = "About"
  url = "about/"
  weight = -107

# social menu links

[[social]]
  name = "github"
  type = "social"
  weight = 1
  url = "https://github.com/jonlimx"
[[social]]
  name = "twitter"
  weight = 2
  url = "https://twitter.com/#"
[[social]]
  name = "linkedin"
  weight = 3
  url = "https://www.linkedin.com/in/#"
[[social]]
  name = "rss"
  weight = 4
  url = "index.xml"`

**Comment by onweru** [comment]
> @onweru Thanks for your time. Sure, I have config.toml, menus.zh.toml and params.toml under xxx/config/_default. I am pasting the configurations as follows:
> 
> **config.toml**
> baseURL = "https://www.jonathanlin.top/"
> languageCode = "zh-cn"
> title = "Standing on the Shoulder of Giants"
> theme = "hugo-clarity"
> DefaultContentLanguage = "zh"
> copyright = "Copyright © {year} Jonathan Lin. All rights reserved."
> 
> **params.toml**
> numberOfTagsShown = 14 # Applies for all other default & custom taxonomies. e.g categories, brands see https://gohugo.io/content-management/taxonomies#what-is-a-taxonomy
> codeMaxLines = 10
> codeLineNumbers = true
> 
> **menus.zh.toml**
> [[main]]
> name = "Home"
> url = ""
> weight = -110
> 
> [[main]]
> name = "Archives"
> url = "post/rich-content/"
> weight = -109
> 
> [[main]]
> name = "Links"
> identifier = "Links"
> weight = -108
> [[main]]
> parent = "Links"
> name = "LinkedIn"
> url = "https://www.linkedin.com/"
> [[main]]
> parent = "Links"
> name = "Twitter"
> url = "https://twitter.com/"
> 
> [[main]]
> name = "About"
> url = "about/"
> weight = -107
> 
> [[social]]
> name = "github"
> type = "social"
> weight = 1
> url = "https://github.com/jonlimx"
> [[social]]
> name = "twitter"
> weight = 2
> url = "https://twitter.com/#"
> [[social]]
> name = "linkedin"
> weight = 3
> url = "https://www.linkedin.com/in/#"
> [[social]]
> name = "rss"
> weight = 4
> url = "index.xml"

Thanks for this. I was expecting to see the repo so that I can test it on the browser. Do you have a link to the repo?

**Comment by jonlimx** [comment]
I have invited you to my repo.

**Comment by onweru** [comment]
@jonlimx, I found what the problem is. Please add this file https://github.com/chipzoller/hugo-clarity/blob/master/exampleSite/config/_default/markup.toml inside `config/_default` directory. I cloned and tested your repo and it should work. Happy blogging.

**Comment by jonlimx** [comment]
@onweru Thanks, it works!  And sorry for maybe a stupid mistake I have made. Thanks again for your time.
