### ISSUE TITLE
[Feature Request] "Notice" block capability 

### ISSUE THREAD

**Issue by dahlsailrunner** [chipzoller/hugo-clarity#198]
I'm about to release an updated version of my blog to use the hugo-clarity theme - super awesome.

I added an additional shortcode to my custom code and was wondering if you'd want to consider adding it here: it's the "notice" type block that you can see here:  https://knowyourtoolset.com/2021/03/authoring-short-targeted-videos/#6-combine-video-with-polished-audio
(it's the green-ish block in the middle of the page)

There are 4 different kinds of notices with different coloring (tip, info, note, and warning).  I had to add the css you see in this file (not the image classes) to make it work:  https://github.com/dahlsailrunner/knowyourtoolset-blog/blob/main/static/css/custom.css

I'm not familiar enough with SASS to have made the required modifications there. 

Would something like this be useful in the theme itself or should I just keep it as a custom element on my blog?

I'm happy to submit a PR (and could take a shot at updating sass to support its needs) if you think it makes sense to include.  I could also include a .vscode snippet (it's in the same repo) that makes it easier to use the shortcode.  (and if i did a PR I would add some doc notes to the readme).

Let me know your thoughts -- and thanks for creating the theme!!!

**Comment by onweru** [comment]
@dahlsailrunner, I think it's a good idea. @chipzoller, what do you think?

**Comment by chipzoller** [comment]
Yes, this would be cool to add, @dahlsailrunner ! These notice blocks are something I actually like in the Docsy theme and had an idea of working on them a while back. Your PR would be most welcome!

**Comment by dahlsailrunner** [comment]
Ok - I'll try to submit something before Monday.  I was not planning on changing the CSS but that would be the biggest question in my mind.  Currently the same coloring is used on these regardless of dark/light mode.  I'll get a PR started and we can iterate if needed.  :)

**Comment by dahlsailrunner** [comment]
PR Submitted!  https://github.com/chipzoller/hugo-clarity/pull/204

Happy to discuss / make revisions.

**Comment by dahlsailrunner** [comment]
PR #204  was merged!
