### ISSUE TITLE
Line height in `post_link` creates non-clickable gap in multiline titles

### ISSUE THREAD

**Issue by rootwork** [chipzoller/hugo-clarity#199]
**I have checked all the prerequisites below and I'm yet experiencing a problem**

- [x] Read the README.md
- [x] Have the extended version of Hugo installed
- [x] Used the exampleSite's config.toml as a reference
- [x] I have included my repository link. Instead of pasting long snippets here.

**Describe the bug**

`<h3>`s have `line-height: 1.35` set on them. When an `<h3>` is also a `post_link`, this creates a non-clickable gap in between multiple lines of text. [My solution](https://github.com/rootwork/rootwork.org/blob/main/hugo/assets/sass/_override.scss#L67-L74). There are probably other ways to do it.

Screenshot before, with `<a>` element highlighted:
![current](https://user-images.githubusercontent.com/79733/129284273-a82af40b-f932-4350-84d8-4feda7b37c55.png)

Screenshot after:
![with-change](https://user-images.githubusercontent.com/79733/129284288-3138e1d0-2ab5-48ac-8286-6c2f333528c4.png)

I realize this is pretty minor, but wanted to suggest it as a refinement.

**Desktop (please complete the following information):**
 - OS: Linux Mint 20.2
 - Browser: FF 91.0

**Comment by rootwork** [comment]
Also, happy to turn this into a PR if my solution looks OK.

**Comment by onweru** [comment]
@rootwork, please proceed.

**Comment by rootwork** [comment]
Sorry for that muddled PR. #201 is the clean one.

**Comment by onweru** [comment]
Thank you @rootwork
