### ISSUE TITLE
Should be able to define default colour mode from config.toml

### ISSUE THREAD

**Issue by vivekkrkarn** [chipzoller/hugo-clarity#20]
Hi,
I think, we should be able to define default colour mode ( light or dark ) from config.toml
thank you for this theme.

**Comment by chipzoller** [comment]
The default color mode is dependent upon the color mode of the client system. If you wish to override this, you can flip the mode switch and the site should remember that within the same session. Still, we will consider the idea.

**Comment by chipzoller** [comment]
Addressed in earlier commit. See [the docs](https://github.com/chipzoller/hugo-clarity#forcing-light-or-dark-mode) for usage details.
