### ISSUE TITLE
rich-content.md prevented the build process

### ISSUE THREAD

**Issue by mochamadboval** [chipzoller/hugo-clarity#207]
**I have checked all the prerequisites below and I'm yet experiencing a problem**

- [x] Read the README.md
- [x] Have the extended version of Hugo installed

**Describe the bug**

I just installed the theme, but failed on the build process. It seems there was an error in **rich-content.md** file. Delete it will fix this problem.
![Screenshot from 2021-09-06 14-02-58](https://user-images.githubusercontent.com/57146067/132176424-e45440f9-0b58-4436-8116-2fc9d7596bd6.png)

**Desktop**
 - OS: elementary OS 6 Odin (Based on Ubuntu 20.04 LTS)
 - Browser: Chrome 93.0.4577.63

**Comment by kevinlv1024** [comment]
yes,I have the same promble.

**Comment by SurprisedCat** [comment]
When render shortcode like 'twitter_simple' or 'vimeo_simple', it needs connecting to a specific server for some data. If you have some network problem (GFW, most commonly), the error shows up. Just delete the related 'Simple Shortcode' in rich-content.md.
