### ISSUE TITLE
_override.sass doesn't take an effect on component styles

### ISSUE THREAD

**Issue by akirillov** [chipzoller/hugo-clarity#212]
**I have checked all the prerequisites below and I'm yet experiencing a problem**

- [x] Read the README.md
- [x] Have the extended version of Hugo installed
- [x] Used the exampleSite's config.toml as a reference

**Describe the bug**

I'm playing with this awesome Hugo theme (kudos for creating it!) and trying to modify some styles by following the README and placing all the changes in the `_override.sass`. However, the changes are not taking any effect. As an example, I'm trying to make the navbar absolute:
```
//<project root>/assets/sass/_override.sass
.nav
  &_header
    position: absolute
```
I think the problem is that the overrides are included at the beginning of the [main.sass](https://github.com/chipzoller/hugo-clarity/blob/master/assets/sass/main.sass#L2) and actually not producing any overrides as the following import of the `components` discards any changes. When I override the `main.sass` and place the overrides import at the end - everything works as expected.

I'm not an expert in web development so please excuse me if I'm doing it in the wrong way. I'd appreciate some guidance on how to override theme styles if it is expected to be done at all.

**Desktop (please complete the following information):**
 - OS: MacOS 10.15
 - Browser: Chrome 93.0

**Comment by onweru** [comment]
@akirillov, I will look into this.

**Comment by onweru** [comment]
@akirillov, I checked this. Turns out, this is not a bug. The behaviour is well documented in the readme https://github.com/chipzoller/hugo-clarity#custom-css-and-js. `_override.sass` file is only supposed to override css variables. To override actual styles use `_custom.sass`.
