### ISSUE TITLE
Feature request: Post relative thumbnail image

### ISSUE THREAD

**Issue by rasmusson** [chipzoller/hugo-clarity#214]
When setting a thumbnail image in post frontmatter you must set the path for the image from the root of the webpage. 
This either means you need to hard code the path for the post directory or put all thumbnails together in a folder.

Would it be possible to instead look for the image relative to the post? This will make it easier to organize images and make it more robust.

**Comment by onweru** [comment]
@rasmusson, please see the comment on #215
