### ISSUE TITLE
Feature Request: Add Comments using Utterenc

### ISSUE THREAD

**Issue by joesan** [chipzoller/hugo-clarity#234]
I'm finding the comments using Utterenc a good option as compared to Disqus. Is there a way to support this out of the box? Any pointers on how to add this? Seems like a simple step to do as per this documentation here:

https://mscipio.github.io/post/utterances-comment-engine/

I can look into this if any suggestions are given?

**Comment by rterakedis** [comment]
@joesan - I just submitted a pull request (#257) to add support for it.   Test it out!

**Comment by chipzoller** [comment]
Closed in #257
