### ISSUE TITLE
Clarity not loading / rendering

### ISSUE THREAD

**Issue by A-d-r-i** [chipzoller/hugo-clarity#239]
**I have checked all the prerequisites below and I'm yet experiencing a problem**

- [x] Read the README.md
- [x] Have the extended version of Hugo installed
- [x] Used the exampleSite's config.toml as a reference
- [ ] I have included my repository link. Instead of pasting long snippets here.

**Describe the bug**
I installed hugo with the .deb package (hugo + extended version : https://github.com/gohugoio/hugo/releases ) and I tested a theme loading SASS.
Unfortunately when loading the page displays this (_example taken from a forum_):
![image](https://user-images.githubusercontent.com/27277698/146727929-1a47de38-e799-40f7-9356-63b6ccf0ced6.png)

**Desktop (please complete the following information):**
 - Debian 10

**Comment by onweru** [comment]
Hi @A-d-r-i, sorry about that happening to you. Umh, would you screenshot the console log ?

**Comment by A-d-r-i** [comment]
Oh you can't imagine that you saved me with this simple question! Thank you very much @onweru!
I found out (thanks to the console which was telling me 404 errors with https://example.com) why it did that: I had modified the `config.toml` at the root of my site and not in `config/_default/config.toml`

It might be necessary to specify in the doc (for novices like me) that it is necessary either:

* modify the config in `config/_default/config.toml`
* move `config/_default/config.toml` in the root of the site

Thanks again! 😊

**Comment by A-d-r-i** [comment]
Last error in the console: 404 with `caret-icon.svg`

I'm on apache2 so I changed the [name of the icons folder](https://github.com/chipzoller/hugo-clarity/issues/74#issuecomment-809756740) and everything works fine except for this one! (I specify that it is in the static and public folder with new name)

**Comment by onweru** [comment]
I will check if there's something we missed with the caret icon

**Comment by chipzoller** [comment]
I just went through this with the example site and it renders fine on my end.

**Comment by A-d-r-i** [comment]
Thanks for your replies!

For me:
```
hugo version
hugo v0.91.0-D1DC0E9A+extended linux/amd64 BuildDate=2021-12-17T09:50:20Z VendorInfo=gohugoio
```

I tried looking for where I was the problem with `grep -w -r -o -n "icons" . `  but nothing really relevant!

**Comment by imtrinity94** [comment]
I am having the same problem. 
PS D:\Hugo\Sites\cloudblogger> D:\Hugo\bin\hugo.exe version
hugo v0.92.0-B3549403 windows/amd64 BuildDate=2022-01-12T08:23:18Z VendorInfo=gohugoio

First, I couldn't run hugo command directly, so I am using D:\Hugo\bin\hugo.exe for everything

Console log:
PS D:\Hugo\Sites\cloudblogger> D:\Hugo\bin\hugo.exe server --disableFastRender
Start building sites …
hugo v0.92.0-B3549403 windows/amd64 BuildDate=2022-01-12T08:23:18Z VendorInfo=gohugoio

                   | EN | PT
-------------------+----+-----
  Pages            | 47 | 29
  Paginator pages  |  0 |  0
  Non-page files   |  0 |  0
  Static files     | 63 | 63
  Processed images |  0 |  0
  Aliases          | 28 | 15
  Sitemaps         |  2 |  1
  Cleaned          |  0 |  0

Built in 123 ms
Watching for changes in D:\Hugo\Sites\cloudblogger\{archetypes,content,data,layouts,static,themes}
Watching for config changes in D:\Hugo\Sites\cloudblogger\config.toml, D:\Hugo\Sites\cloudblogger\config\_default, D:\Hugo\Sites\cloudblogger\config\_default\menus
Environment: "development"
Serving pages from memory
Web Server is available at http://localhost:1313/ (bind address 127.0.0.1)
Press Ctrl+C to stop
