### ISSUE TITLE
Currrently there is no vertical spacing between the tags in a post. 

### ISSUE THREAD

**Issue by Dog-In-a-Tank** [chipzoller/hugo-clarity#245]
**I have checked all the prerequisites below and I'm yet experiencing a problem**

- [X ] Read the README.md
- [ X] Have the extended version of Hugo installed
- [ X] Used the exampleSite's config.toml as a reference
- [ ] I have included my repository link. Instead of pasting long snippets here.

**Describe the bug**
![Screenshot 2021-12-24 at 11 26 35](https://user-images.githubusercontent.com/91974862/147349053-2759fa5e-0979-4022-9461-1eac579d4f4b.png)

The tags in a post sit on top of each other with no vertical space between them as shown in the picture. 

> Avoid long-winded descriptions

**Desktop (please complete the following information):**
 - OS: [e.g. iOS 14, Windows 10]
 - Browser [e.g. chrome 76, safari 13]

**Comment by chipzoller** [comment]
Closed with fix.
