### ISSUE TITLE
Using the Caret symbol for superscript does not appear to work 

### ISSUE THREAD

**Issue by Dog-In-a-Tank** [chipzoller/hugo-clarity#254]
**I have checked all the prerequisites below and I'm yet experiencing a problem**

- [ ] Read the README.md
- [ ] Have the extended version of Hugo installed
- [ ] Used the exampleSite's config.toml as a reference

**Describe the bug**

Using the caret symbol  10 ^nd^ to show text that should be in superscript does not appear to work when creating a post. However using < sup > HTML tag works. missing CSS ?

**Comment by onweru** [comment]
@Dog-In-a-Tank, please search for a solution in the community https://discourse.gohugo.io/t/superscript-doesnt-work-unsafe-true/30535/14

**Comment by onweru** [comment]
It's a Hugo markdown renderer thing
