### ISSUE TITLE
jane-doe and other baggage

### ISSUE THREAD

**Issue by jlabonski** [chipzoller/hugo-clarity#261]
I noticed that when I build a site, it drags along various default favicons from the theme unless explicitly overridden, as well as a few items from an images folder:

* jane-doe.png (generic avatar)
* thumbnail.png (rancher diagram)

The other two files in `images/` (sun.svg, night-moon.png) are for the toggle.

In addition, unless explicitly overriden, I'll get the clarify favicons of the weird java-like coffeecup. It's a bit of unexpected behavior and you may want to either zap these or provide a list of included files and how they must be placed in the `/icons/` subdirectory.

I'm using the theme as a module, if that helps any.

**Comment by chipzoller** [comment]
@onweru I've noticed this as well on other sites (especially the Rancher diagram). Do we just remove those PNG files?

**Comment by chipzoller** [comment]
Closed in https://github.com/chipzoller/hugo-clarity/commit/352b26464ba64faaf6ea8879445b17545826e925
