### ISSUE TITLE
Tanslation Hint at bottom of page - where/how to remove? 

### ISSUE THREAD

**Issue by winxthecat** [chipzoller/hugo-clarity#262]
**I have checked all the prerequisites below and I'm yet experiencing a problem**

- [X ] Read the README.md
- [X ] Have the extended version of Hugo installed
- [X ] Used the exampleSite's config.toml as a reference

**Describe the bug**

On a page that is translated, the hint to the available translation is too much. Can this be removed? Or at least, where do I get rid if the | ? As I do only use German/English and not a third language.

![grafik](https://user-images.githubusercontent.com/98853115/153778646-593f8172-a98c-4d1b-b1c0-0e76d15b653e.png)

> Avoid long-winded descriptions

**Desktop (please complete the following information):**
Windows 10
Firefox 96
also experienced on Edge browser

**Comment by onweru** [comment]
@winxthecat,

If you really would rather not have them, you can remove them here https://github.com/chipzoller/hugo-clarity/blob/14cc9cc7d1ac4d439b7fc9e807de36cf860e7cf9/layouts/_default/single.html#L51
