### ISSUE TITLE
Feature request: Allow setting meta keywords from `params.toml`

### ISSUE THREAD

**Issue by rootwork** [chipzoller/hugo-clarity#263]
Thanks for adding meta keywords support in https://github.com/chipzoller/hugo-clarity/commit/6e9e7f8a2a59d01304dd1aae65b67bfb1fc981a8 to address #258 

From what I can see, with that addition those keywords can only be set for the homepage in the content file (`content/_index.md`) but not in the `params.toml` file. Since the site description can be set in `params.toml` (as well as the content file), and is used for a similar SEO-related purpose, it would be nice to be able to set the keywords there as well.

**Comment by rootwork** [comment]
I *can* work on this, but was sort of hoping @onweru would since he added the params in the first place :)

**Comment by onweru** [comment]
@rootwork, please help. My schedule is crazy 😃

**Comment by rootwork** [comment]
PR ready to review!
