### ISSUE TITLE
Docs: Getting up and running > Option 1: needs a few clarifications

### ISSUE THREAD

**Issue by rootwork** [chipzoller/hugo-clarity#27]
**I have checked all the prerequisites below and I'm yet experiencing a problem**

- [x] Read the README.md
- [x] Have the extended version of Hugo installed
- [x] Used the exampleSite's config.toml as a reference

**Describe the bug**

Unless I'm misreading option 1 or missing something, following its steps will create the following directory structure:

`yourSiteName`
`yourSiteName/config.toml` [default new site config]
`yourSiteName/exampleSite`
`yourSiteName/exampleSite/config.toml` [Hugo Clarity's exampleSite config]
`yourSiteName/themes/hugo-clarity`

Thus when you run `hugo server`, you'll still be in the root project folder (`yourSiteName` above) and it will use the default new site config to render the site, not the example site's. If you `cd` into `exampleSite` and try to run `hugo server`, it'll complain that the theme isn't in a subdirectory.

I think instead of
`cp -a themes/hugo-clarity/exampleSite/ .`
perhaps you meant
`cp -a themes/hugo-clarity/exampleSite/* .`
?

Additionally, as a final step before running `hugo server` I would suggest instructing users to edit the `config.toml` file and change the `baseurl`, or CSS files will be broken.

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04
 - Browser Firefox 80.0

**Comment by onweru** [comment]
@rootwork, I have followed [the steps in option 1](https://github.com/chipzoller/hugo-clarity#option-1-recommended) as they're and everything works as intended. I'm positive @chipzoller did the same while doing the README writeup.
