### ISSUE TITLE
Did I meet bugs,or I lost something??

### ISSUE THREAD

**Issue by github-lym** [chipzoller/hugo-clarity#277]
**I have checked all the prerequisites below and I'm yet experiencing a problem**

- [ ] Read the README.md
- [x] Have the extended version of Hugo installed
- [x] Used the exampleSite's config.toml as a reference
- [ ]  I have included my repository link. Instead of pasting long snippets here.

I installed the theme by  **Option 1 & 2** in [Getting up and running](https://github.com/chipzoller/hugo-clarity#getting-up-and-running).

**And all have same result.**

1.
/config/_default/params.toml
set codeMaxLines = 7
But the code always shows full content,can not been collapsed.
![notfold](https://user-images.githubusercontent.com/69377506/160145662-d31f8a3a-410b-41de-8cd7-e746fd727d08.JPG)

2.
/config/_default/params.toml
set usePageBundles = true
and my webcontent tree is below:
```
content
│  about.md
│  about.pt.md
│  archives.md
│  search.md
│  _index.md
│
├─homepage
│      about.md
│      index.md
│      work.md
│
└─post
    │  emoji-support.md
    │  markdown-syntax.md
    │  markdown-syntax.pt.md
    │  math-typesetting.md
    │  notices.md
    │  placeholder-text.md
    │  rich-content.md
    │  _index.md
    │
    └─2022
            2.png
            index.md
```

I added `2022` folder that has 'index.md' ,`2.png`  in it.
I want to show a image => `![](2.png)` in index.md
It did not show.
![001](https://user-images.githubusercontent.com/69377506/160073805-2d984739-2ee0-4c99-85c8-6edef187ccda.PNG)

I put the 2.png in the `content` folder,it will show.  
![002](https://user-images.githubusercontent.com/69377506/160073809-5d2ccbe6-9ff7-40f4-b77e-639776205dc5.PNG)

Any ideas??

**Comment by chipzoller** [comment]
I think a more thorough explanation is needed here.

**Comment by github-lym** [comment]
You are so kind.
I updated the description,is it better?
If not clear enough,please tell me,
Thanks!

**Comment by github-lym** [comment]
Simplely,two problem.

1. 
I want use Page Bundles, set usePageBundles = true.
In the `content\post\` ,add a folder named `2022`, in `2022` add `index.md` & `2.png`.
I writed `![](2.png)` in `index.md` ,but It did not show.

2. 
In code block,it always shows full code,can not fold(collapse).

I installed the theme by  **Option 1 & 2** in [Getting up and running](https://github.com/chipzoller/hugo-clarity#getting-up-and-running), and different machines.
**And all have same result.**

**Comment by rootwork** [comment]
For item 1 in the most recent comment - I think #271 will fix this.

For item 2 in the most recent comment - going back to the screenshot at the top, it looks like 88 lines are being displayed AND the expansion icon ("...") is showing. I don't know enough about that code to know why; maybe JS isn't loading?

**Comment by github-lym** [comment]
> For item 1 in the most recent comment - I think #271 will fix this.
Yes!! You are right!!
I add the code in  `layouts/_default/_markup/render-image.html`, the image been shown!!
So it is a bug.

> For item 2 in the most recent comment - going back to the screenshot at the top, it looks like 88 lines are being displayed AND the expansion icon ("...") is showing. I don't know enough about that code to know why; maybe JS isn't loading?

Because I am not a coder,so I do not know why either.
The live demo can toggle to show full code block or not.
I do not know what should do.
![Toggle block expansion/contraction (dynamic)](https://github.com/chipzoller/hugo-clarity/raw/master/images/syntax-block.gif)

**Comment by chipzoller** [comment]
Filed an issue for the code max lines at #280

**Comment by rootwork** [comment]
For clarity I am going to go ahead and close this issue, since from the original report the first item is now captured in #280 and the second was fixed.
