### ISSUE TITLE
Feature Request: Provide a git-trackable way to override theme variables/sass/js

### ISSUE THREAD

**Issue by rootwork** [chipzoller/hugo-clarity#28]
In [custom CSS and JS in the README](https://github.com/chipzoller/hugo-clarity#custom-css-and-js) you explain how to add Sass and JS to the theme, and how to override color variables: By editing files within the Hugo Clarity theme.

I appreciate that you created the `custom.sass` and `custom.js` files.

But modifying these files presents a problem: You either have to choose to continue using the theme as a git submodule (in which case you can't track modifications) or you have to commit the theme directory as a regular part of your own git repo (in which case you can't update the theme as a submodule).

Changing the color variables is worse: Now you're hacking the theme files themselves, meaning you have the problem above _and_ if you ever update the theme, there will be merge conflicts.

Is there a way to provide support within the theme for custom Sass, JS and variable files **within the parent project's directory**? Perhaps in an `assets` directory of its own?

While it's true that right now you could override the CSS or JS in the parent project's directory, you can only do it by loading additional CSS/JS files (as you point out in that section of the README). And the only way to override the color variables -- because they're used throughout the theme's Sass files -- would be to replicate _all_ the rendered CSS that those color variables touch.

What do you think?

**Comment by rootwork** [comment]
There's a PR that does this for you to review.

Also noting that this is a followup to #7.

**Comment by onweru** [comment]
Thanks for contributing @rootwork! I agree. Will review PR asap.
