### ISSUE TITLE
[Bug] Code block max lines regression

### ISSUE THREAD

**Issue by chipzoller** [chipzoller/hugo-clarity#280]
**I have checked all the prerequisites below and I'm yet experiencing a problem**

- [x] Read the README.md
- [x] Have the extended version of Hugo installed
- [x] Used the exampleSite's config.toml as a reference
- [x] I have included my repository link. Instead of pasting long snippets here.

**Describe the bug**

In a recent commit, the code block max lines isn't being obeyed.
From [here](https://neonmirrors.net/post/2021-06/policy-k8s-customresources/).

Correct:

![image](https://user-images.githubusercontent.com/29008123/160302211-f284b29c-2602-40fe-9c21-8174799b4e3f.png)

Incorrect:

![image](https://user-images.githubusercontent.com/29008123/160302228-02725955-a3a5-4d1e-98f9-2ba92cb26d85.png)

Also note the elipses (three dots) at the bottom of the fully expanded code block in the incorrect screenshot. These should not be visible when a code block is fully extended.

**Comment by georgew509** [comment]
I just wanted to make sure that this related code block issue is covered.

If I have a block of code that is 150 lines long. The entire 150 lines are displayed instead of just the “codeMaxLines.” And I also see the three dots at the end of the 150-line code block.

**Comment by chipzoller** [comment]
@onweru we're still having issues here. Can you take a look?

**Comment by georgew509** [comment]
If this helps ...

I have an example at:
  https://altoplace.org/posts/2021/configure-apache-and-php-fpm-on-macos/#using-port-80

And I added my site code to GitHub:
  https://github.com/georgew509/clarity-aporg

**Comment by chipzoller** [comment]
@georgew509 this should be fixed (thanks to @onweru 🙏)

**Comment by georgew509** [comment]
Thanks! I’ll try it out when I get home from vacation. 

George
