### ISSUE TITLE
Search Page 404

### ISSUE THREAD

**Issue by rianbk** [chipzoller/hugo-clarity#286]
**I have checked all the prerequisites below and I'm yet experiencing a problem**

- [ Y] Read the README.md
- [ Y] Have the extended version of Hugo installed
- [Y] Used the exampleSite's config.toml as a reference
- [N] I have included my repository link. Instead of pasting long snippets here.

I know that search is a beta feature, but upon updating and enabling the feature. Search works find and starts autosuggesting items. but if i hit enter to go to the search page i get a 404

![image](https://user-images.githubusercontent.com/3753933/163706540-f93f7f06-854f-495b-ab6f-15a9ddef57ae.png)

Live site: https://rianbk.com

**Comment by onweru** [comment]
@rianbk, do you have a `search.md` file under your content folder?

**Comment by onweru** [comment]
```
├── content
│   ├── _index.md
│   ├── search.md
│   ├── posts
```

**Comment by rianbk** [comment]
thanks, thats fixed my issue
