### ISSUE TITLE
Search shows no results if more than one entry in mainSections

### ISSUE THREAD

**Issue by robe2** [chipzoller/hugo-clarity#290]
**I have checked all the prerequisites below and I'm yet experiencing a problem**

- [ x] Read the README.md
- [ x] Have the extended version of Hugo installed
- [ x ] Used the exampleSite's config.toml as a reference
- [ ] I have included my repository link. Instead of pasting long snippets here.

**Describe the bug**

Search does not find anything if more than one directory specified in mainSections.

I have 3 directories: post, pages, events

If I put any of the below in my params.toml file, then it can search just that section
`
mainSections = ["post"] `

or
`mainSections = ["events"] `

or
`mainSections = ["pages"] `

However if I put all of them in like so:

`mainSections = ["post", "events", "pages"] `

Then search finds nothing.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome, Firefox

**Comment by rootwork** [comment]
@onweru Can you take a look when you get a chance?

**Comment by timatlee** [comment]
I don't know if this can be considered a related question, but I would be interested to understand how to get the passive search function to search multiple sections (ie, "post" and "recipe") without having to set "recipe" as a mainSection.

I think once I understand how multiple mainSections are searched, I could probably set a config for `searchSections` and submit a PR...

**Comment by onweru** [comment]
@timatlee, at the moment, the search function should search the [entire site](https://github.com/chipzoller/hugo-clarity/blob/ede406b64d25d3ba36b0e33411a7a53a95129c67/layouts/_default/index.json#L4). This [may not be ideal](https://github.com/onweru/compose/issues/15). First I'll explore the anomaly described by @robe2.

As an improvement, I might introduce the concept of search scope. For granular search

**Comment by timatlee** [comment]
@onweru I do see the content for the whole site being generated in `index.json`, but the passive search seems to be limited to content within the "posts" content type.  At least, the experience that I'm seeing at the moment does not surface the content in the "recipe" type:
![image](https://user-images.githubusercontent.com/1431914/168443674-5b49dffa-5373-49b1-8a9e-f737c5e6366c.png)

I should have annotated that image, but the URL path is showing that I'm in `/recipe`, but typing in a search query for a post that is clearly listed is not shown in the search results.

Limited screenshot showing that the post in question is in `index.json`:
![image](https://user-images.githubusercontent.com/1431914/168443696-be1b85d1-7146-44a3-9d3b-8bb2bd8be5fa.png)

If I change `/layouts/partials/search/widget.html`'s data-scope to "recipe", I get the opposite behaviour - searching just the recipe's, but not the "post" content.

I'm not sure how I can illustrate this, to be honest.

The same behaviour exists using the exampleSite and the 'page' content types - the About page is in index.json, but does not surface in the search results, though in that case, the About page in index.json does not have a section value.

I understand that the search behaviour for the whole site may not be ideal. Once the initial anomaly is addressed, I thought I would take an attempt at a way to define the search scope within the site's configuration...  but at the instant in time, I don't have a good understanding of how the search component works :)

Thanks for your response!

**Comment by onweru** [comment]
@timatlee, thanks for this feedback. I will ready a fix asap.

**Comment by onweru** [comment]
@timatlee, watch out for when #301 is merged. It will fix your issue.

**Comment by timatlee** [comment]
@onweru Thanks! Great fix, and seems like it strikes a good balance of site-wide versus section-wide searching. Great work!

**Comment by onweru** [comment]
Thanks, @timatlee. I will close this issue now. Keep an eye on #308 for further improvements on section-scoped search.
