### ISSUE TITLE
when running hugo server locally, css does not work due to integrity.

### ISSUE THREAD

**Issue by dstamen** [chipzoller/hugo-clarity#3]
to get it to work locally on my mac i had to disable the data integrity lines in baseof.html

**Comment by chipzoller** [comment]
I was not able to reproduce this by following both option #1 and option #2 in the readme. This was tested on Mac 10.14.6 with Hugo extended v0.74.2. Can you describe any steps to reproduce this issue?

**Comment by onweru** [comment]
> to get it to work locally on my mac i had to disable the data integrity lines in baseof.html

@dstamen, please ensure that you've cleared the resources directory. The data integrity ought to work with no issues

**Comment by dstamen** [comment]
this is on macos 10.15.6 and hugo 73.0

**Comment by chipzoller** [comment]
Closing for now since issue cannot be reproduced on exampleSite content.

**Comment by chipzoller** [comment]
Could not reproduce on Mojave with Hugo v0.74.3 and the exampleSite instructions in option 2.
