### ISSUE TITLE
Asset variable paths assume particular directory structure

### ISSUE THREAD

**Issue by rootwork** [chipzoller/hugo-clarity#30]
**I have checked all the prerequisites below and I'm yet experiencing a problem**

- [x] Read the README.md
- [x] Have the extended version of Hugo installed
- [x] Used the exampleSite's config.toml as a reference

**Describe the bug**

[`_variables.sass`](https://github.com/chipzoller/hugo-clarity/blob/master/assets/sass/_variables.sass) has paths for fonts, icons and images with a leading `../`. This assumes a particular directory structure in the rendered site. If, for instance, your blog posts have paths like `posts/2020/09/01/blog-post-title`, those asset paths are not going to be correct and the assets won't load.

It seems to me like these paths should be set either from the root directory (of the rendered website, not the Hugo root), or using the `baseurl` Hugo variable to give an accurate reference to the assets.

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04
 - Browser: Firefox 80.0.1

**Comment by onweru** [comment]
Umh, that doesn't actually apply in the way you have described. Those paths are only relative to the generated css file, which will always link to the same directory for all pages.

**Comment by rootwork** [comment]
You're right, that was my misunderstanding about the relative path. Weirdly, the font _was_ broken for me until I changed the path to start at the webroot, but maybe that was something peculiar to my server.

**Comment by onweru** [comment]
Interesting 🤔, what was your baseURL in the config? Curious

**Comment by rootwork** [comment]
Initially I think it was just the example.com that ships with the default config, but even after I changed it to my actual domain it seemed to still not show up. I'll try fiddling with it and see if I can at least see what errors the server gives me when it's got the relative path.

**Comment by onweru** [comment]
Look forward to what you unearth. Thanks again for contributing.
