### ISSUE TITLE
Code block "Copy to clipboard" function is not working

### ISSUE THREAD

**Issue by georgew509** [chipzoller/hugo-clarity#312]
**I have checked all the prerequisites below and I'm yet experiencing a problem**

- [X ] Read the README.md
- [X] Have the extended version of Hugo installed
- [X] Used the exampleSite's config.toml as a reference
- [ ] I have included my repository link. Instead of pasting long snippets here.

- I have deployed my [website](https://altoplace.com)  using the Clarity theme Option 2, Hugo Modules. I noted that a lot of work was done while I was gone on vacation.

However, I am still having an issue with Code blocks. The "Copy to clipboard" function is not working for me. I am on macOS using Safari. I also have tried using Chrome. [Here](https://altoplace.com/posts/2021/configure-apache-and-php-fpm-on-macos/#using-port-80) are some example code blocks on my site.

The "Copy Code" icon blinks when I click on it, but I don't see the code when I try to paste it to a file.

Here are some details about my development environment:

george@imac1:~
$ hugo version
hugo v0.99.1+extended darwin/amd64 BuildDate=unknown

george@imac1:~
$ go version
go version go1.18.2 darwin/amd64

george@imac1:~/Hugo/clarity
$ hugo mod graph
clarity github.com/chipzoller/hugo-clarity@v0.0.0-20220519120232-e511e14db7a1

Thanks for all the hard work that's been done over the last couple of weeks.

**Comment by jbowdre** [comment]
I'm seeing the same as well with `hugo v0.96.0+extended linux/amd64` and a local clone of this repo as of [e511e14](https://github.com/chipzoller/hugo-clarity/commit/e511e14db7a11b726ccc6c4456bf5ec5ebdd3720). 

Other code functions work fine, just not the copying.

**Comment by chipzoller** [comment]
cc @onweru

**Comment by chipzoller** [comment]
Closed by #298
