### ISSUE TITLE
Feature: add CI/CD workflows

### ISSUE THREAD

**Issue by ShoGinn** [chipzoller/hugo-clarity#318]
**I have checked all the prerequisites below and I'm yet experiencing a problem**

- [x] Read the README.md
- [x] Have the extended version of Hugo installed
- [x] Used the exampleSite's config.toml as a reference
- [x] I have included my repository link. Instead of pasting long snippets here.

**Describe the bug**

I have noticed during my development of this theme that there are easily caught problems if you just run it through a workflow.

Propose: use the workflows I recommend in my repo.

https://github.com/ShoGinn/hugo-clarity/tree/add_workflows

In the repo you see that I tried to fix the test.yml and incorporate an html linter.

**Comment by ShoGinn** [comment]
With these workflows you can see errors that exist currently in the theme for the exampleSite that should be remedied. 

(essentially any thumbnail with a relative url has a 404 error)

**Comment by ShoGinn** [comment]
@rootwork I concur with your assertions, the html-proofer is kinda the gold-standard and I think in a build environment we aren't making it a pre-req but just an executable test.

Standing by for approval.

**Comment by chipzoller** [comment]
I also think these are good things. Contributions would be most welcome to help improve the experience with Clarity!

**Comment by rootwork** [comment]
@ShoGinn Would you like to make a PR for these? If not I can make one based on your workflows, but since it's your idea I wanted to invite you to take the credit 🥇
