### ISSUE TITLE
"Series" is not visible on the Side Bar

### ISSUE THREAD

**Issue by trnrao** [chipzoller/hugo-clarity#33]
**I have checked all the prerequisites below and I'm yet experiencing a problem**

- [Yes ] Read the README.md
- [Yes] Have the extended version of Hugo installed
- [Yes ] Used the exampleSite's config.toml as a reference

**Describe the bug**
"Series" is not visible on the Side Bar. Categories and Tags are visible. But in the Demo URL, ont he Side Bar, Series is vivible. I tried to check various options in config.toml, but could not get to make it visible on my local version,

**Desktop (please complete the following information):**
 - OS: [Windows 10]
 - Browser [Chrome 85]

**Comment by trnrao** [comment]
By going through Sidebar.html code carefully, I have understood that I did not copy the contents of configTaxo.toml to config.toml file. After doing the same, now I getting Series visible on the Side Bar.

Please consider this as Closed.

This is an amazing theme on Hugo and I have been searching for a long time for a blog with { Series, Category, Tags } for a long time. This is really really helpful. Thank you so much for making this available to the community. 

One quick question, at the footer of the blog, what cr5edit/copyright should I give to this theme/authors? Or isn't no such requirement? Kindly help as I am going use this for my blog and publish very soon.

**Comment by onweru** [comment]
> By going through Sidebar.html code carefully, I have understood that I did not copy the contents of configTaxo.toml to config.toml file. After doing the same, now I getting Series visible on the Side Bar.
> 
> Please consider this as Closed.
> 
> This is an amazing theme on Hugo and I have been searching for a long time for a blog with { Series, Category, Tags } for a long time. This is really really helpful. Thank you so much for making this available to the community.
> 
> One quick question, at the footer of the blog, what cr5edit/copyright should I give to this theme/authors? Or isn't no such requirement? Kindly help as I am going use this for my blog and publish very soon.

@trnrao,

Thanks for the feedback. We’re glad 😃 to know that you find the theme useful. Please proceed freely with the attribution. Anything goes.
