### ISSUE TITLE
Need to add result page to enable search when upgrading

### ISSUE THREAD

**Issue by rasmusson** [chipzoller/hugo-clarity#335]
When upgrading to the newest version and enabled search I get 404 on the result pages. This was resolved after adding the search.md page from the example site. This should be in the documentation for search if it is not possible to include in the theme. 

I notices the same you have the same problem on your reference site https://neonmirrors.net/search/?query=ds&scope=post

**Comment by chipzoller** [comment]
Search seems to be working fine on neonmirrors.net. What problem are you seeing?

As to the upgrade instructions, you're absolutely right. Would you like to submit a PR which adds these instructions?

**Comment by rasmusson** [comment]
If you type a search term and hit enter you get a 404, same as I had before adding the search.md on my site. 
I'll can write some instructions

**Comment by chipzoller** [comment]
I don't have that problem. Hitting Enter does nothing but search results are returned in the search area.

**Comment by chipzoller** [comment]
Oh wait, you're right. It doesn't do anything on Firefox but it does on Brave.

**Comment by rasmusson** [comment]
Now when I try I get the search result page. Strange. You didnt do any changes?
I submittet a PR for the documentation change

**Comment by chipzoller** [comment]
I updated neonmirrors.net with the search page.
