### ISSUE TITLE
Editing footer breaks links menu in header

### ISSUE THREAD

**Issue by AndrewRichardson2** [chipzoller/hugo-clarity#35]
Hi,

Firstly, awesome theme!

I've noticed that if you modify or remove the following code in footer.html: `<span class = 'year'></span>`, it breaks the links menu in the header.  The links menu no longer folds out and will act as a home button when you click it.

I've been able to validate this locally by commenting out that part of the line (or the entire line).

Figuring out why this is happening is beyond my skills with Hugo but I wouldn't expect an edit in the footer to break something in the header, so it took a little while to track down.

**Comment by onweru** [comment]
@AndrewRichardson2, thanks... will remedy that asap
