### ISSUE TITLE
Is there an easy way to set default theme to light?

### ISSUE THREAD

**Issue by rahulwagh** [chipzoller/hugo-clarity#36]
**I have checked all the prerequisites below and I'm yet experiencing a problem**

- [x] Read the README.md
- [x] Have the extended version of Hugo installed
- [x] Used the exampleSite's config.toml as a reference

**Describe the bug**

I really liked the hugo-clarity theme and would like to use for my blog but is there a way or global variable which i can set, so that the default theme layout is always **light**. 

In the current setup it always defaults to **dark** theme and I somehow felt it **light** theme should have be the default one.

I know there has been an enhancement request to make it a part config.toml but for the time being if can be somehow controlled via variables.sass or base.sass? 

**Desktop (please complete the following information):**
 - OS: [e.g. Ubuntu]
 - Browser [firefox 80.0.1]

**Comment by chipzoller** [comment]
The only way the theme would default to dark is if your underlying system is using dark theme. Clarity will pick that up from the user and apply it to the site. So if visiting users aren't in dark mode, it won't default to dark but to light.

**Comment by rahulwagh** [comment]
Okay, thanks for the information, I wasn't aware of that **"It depends on the underlying system"** but it sounds great.

If it's okay than I have one more suggestion - In the dark mode the theme switch button gets lost somewhere in the background-color

![Screenshot from 2020-09-13 18-51-42](https://user-images.githubusercontent.com/6808425/93022585-c721e700-f5f2-11ea-812f-5fc37f6de09f.png)

But its clearly visible in the light theme, 

![Screenshot from 2020-09-13 18-56-54](https://user-images.githubusercontent.com/6808425/93022627-ef114a80-f5f2-11ea-8d0e-df457142de02.png)

can we improve it so that it is clearly visible in the dark mode also?

**Comment by chipzoller** [comment]
Are you specifically referring to the globe icon on the slider or the shaded background on which it's placed?

**Comment by hankyo91** [comment]
i have same issue😥
my os and firefox themes are dark
but i like to have light theme as default for my blog visitors
btw, this hugo theme is awesome, thank you guys for developing it❤️

**Comment by chipzoller** [comment]
> i have same issue😥
> my os and firefox themes are dark
> but i like to have light theme as default for my blog visitors

So there again, users who visit your site using this theme will experience dark/light depending on **their** system settings. This goes for all OS types. We probably should add something to README which explains this since I don't see it mentioned anywhere as a feature.

**Comment by onweru** [comment]
Will add something soon that will strike a good compromise
