### ISSUE TITLE
Theme breaks when deploying via netlify

### ISSUE THREAD

**Issue by AndrewRichardson2** [chipzoller/hugo-clarity#37]
Hi,

I have an issue where the theme seems to break when deploying my site with netlify.  I'm using the latest version of the theme and Hugo 0.75.0 extended.  The site and theme render fine when running locally.  However when built via netlify, the build succeeds but the site looks like this: https://5f60b89d250b6d000748b738--vigilant-raman-d8e917.netlify.app/

I have not had this issue with any other themes including the theme I have reverted to, which is why I'm raising it as an issue as the problem seems to be specific to hugo-clarity.  I'm not sure where to look next.  Any thoughts or ideas?

**Comment by onweru** [comment]
@AndrewRichardson2,

The theme breaks on netlify because you're using "https://virtualslices.com/" as your baseURL. From your `config.toml` file, tweak it to "https://5f60b89d250b6d000748b738--vigilant-raman-d8e917.netlify.app/" or just root i.e "/".

**Comment by AndrewRichardson2** [comment]
Hi @onweru,

Thanks so much for helping me out with that.  I've set the baseurl to "/" and it now works perfectly.  The weird thing is that previously when I had seen the issue it was on my actual site, where the baseurl string was correct.  Either way, seems like setting it at root works!  Thanks again!
