### ISSUE TITLE
[Bug] CORS error when using www. subdomain, .css and .js files not loading

### ISSUE THREAD

**Issue by ChadThackray** [chipzoller/hugo-clarity#375]
### I confirm:

- [X] I am running the [extended version of Hugo version 0.91.0 or above](https://github.com/chipzoller/hugo-clarity/blob/master/README.md#prerequisites) to build my site.
- [X] I have read the [Hugo Clarity theme documentation](https://github.com/chipzoller/hugo-clarity/blob/master/README.md).
- [X] I have used the [example site's config files](https://github.com/chipzoller/hugo-clarity/tree/master/exampleSite/config/_default) as reference.
- [X] I have reviewed [other issues in this repository](https://github.com/chipzoller/hugo-clarity/issues) and mine is not recorded.

### Hugo version

hugo v0.102.0-DEV-7efb35680f4deb82773554be9eb3188d47e6ee0d+extended linux/amd64 BuildDate=2022-08-26T16:50:51Z

### Where is this bug showing up?

In the browser: Hugo builds the site, but something doesn't look right.

### Operating system

Linux Mint 20.3

### Browser (if applicable)

Brave v1.43.89

### Current behavior

CORS error when accessing the `www.domain.com` subdomain.

The error also seems to prevalent on the demo site. If you access `www.neonmirrors.net` the .css and .js static content won't load. Images seem to be fine. 

### Expected behavior

The static content should load without any additional configuration by the user in nginx, apache, etc.. I'm using the `m10c` theme for another website of mine and it loads the static content for both domains with no issues.

### Steps to reproduce

See the `www.` subdomain of the demo site

**Comment by onweru** [comment]
@ChadThackray, @chipzoller,  I think in your server configurations, you ought to configure 301 redirects  from the apex domain (no-www) to www, or vice versa. At least it's the  standard practice

**Comment by ChadThackray** [comment]
Thanks @onweru !

> @ChadThackray, please ensure that in your `config.toml` file, the `baseURL` entry has the `www.`, else you will continue to observe the issue(s) you have described 👆🏼

I tried this before and got the converse issue, then only `www.domain.com` worked and not `domain.com`. 

> @ChadThackray, @chipzoller, I think in your server configurations, you ought to configure 301 redirects from the apex domain (no-www) to www, or vice versa. At least it's the standard practice

Oh ok, didn't know this was the standard procedure. Still strange that it worked for some other hugo themes but not for this one.

Hopefully this issue will help anyone having the same problem in the future.

**Comment by rootwork** [comment]
Going to mark this as fixed given the last comment.
