### ISSUE TITLE
Dark mode text colour & code fence highlighting colour

### ISSUE THREAD

**Issue by AndrewRichardson2** [chipzoller/hugo-clarity#38]
Hi,

Having played around with the theme for a few days, I have some usability suggestions:

1) In dark mode, I think the text colour of #FFFFFF can become a bit straining on the eyes.  In clarity, the predominant text colour for dark mode is #ADBBC4, and I think making this the default (or making it configurable) would be an improvement.
2) When highlighting lines in a code fence with line numbers enabled, the line numbers are extremely difficult to read because the colours of the highlight and the line number are too similar.  This is worse when in dark mode because the code fence highlight colour is lighter, reducing contrast even further.  A possible solution would be to make the line number colour on a highlighted line the same colour as the text (#FFFFFF).

Thanks for the great work with the theme, it's awesome!

**Comment by razonyang** [comment]
Agreed, any news？

**Comment by chipzoller** [comment]
@onweru let's circle up on this. I've heard similar requests for code coloration (in-line, not blocks) in dark theme. We either need to implement now, table for 2.0 milestone, or close.

**Comment by onweru** [comment]
This issue is still in play. The concerns raised are perfectly reasonable.
