### ISSUE TITLE
social urls missing from config.toml

### ISSUE THREAD

**Issue by dstamen** [chipzoller/hugo-clarity#4]
social usernames for github/linkedin/twitter in header are missing from config.toml

**Comment by onweru** [comment]
@dstamen 

Those are supposed to be on [this _social yaml_  >> see the exampleSite](https://github.com/chipzoller/hugo-clarity/blob/master/exampleSite/data/social.yaml). Please use the [exampleSite](https://github.com/chipzoller/hugo-clarity/blob/master/exampleSite/data/social.yaml) as a guide. If something is vague, please look through __the READme__.

**Comment by dstamen** [comment]
I see it there, but it should be parameterized in the config.toml (most if
not all) themes try to make all settings in a single config and then can be
ported/reused in the other sub modules. ill make the changes there for now.

**Comment by chipzoller** [comment]
Should consider merging the `social.yaml` contents into `config.toml` so there is a single file used to control this typical theme functionality.
