### ISSUE TITLE
How to edit the social icons. 

### ISSUE THREAD

**Issue by Abdulee** [chipzoller/hugo-clarity#41]
Hello,
Lets say I want to use a different selfmade icon like I don't want linkedin  and maybe want an email icon. How can I do it.

**Comment by tcarreira** [comment]
Hi @Abdulee 
Check for the file `layouts/partials/icons.html`. You may change entries or add new ones.

You may check this commit (another repo) what I did: https://github.com/Marmita-de-Redon/hugo-redon-podcast/commit/04670ec087c52f990c5b6fb68af86e8f9ecca0f1

**Comment by chipzoller** [comment]
PR merged closing the issue.
