### ISSUE TITLE
[Feature] Mastodon profile support

### ISSUE THREAD

**Issue by stdevel** [chipzoller/hugo-clarity#413]
### I confirm:

- [X] I have read the [Hugo Clarity theme documentation](https://github.com/chipzoller/hugo-clarity/blob/master/README.md).
- [X] I have reviewed [other issues in this repository](https://github.com/chipzoller/hugo-clarity/issues), and this feature has not already been requested.

### Type of feature (check all that apply)

- [X] Site functionality
- [X] Design (styling)
- [ ] Site performance
- [ ] Accessibility
- [ ] Translations and internationalization (i18n)
- [ ] Code improvements
- [ ] Other (please describe below)

### Describe the feature

It would be nice to have the possibility to specify a Mastodon profile in `params.toml` in addition to Twitter and others.

### Preferred solution

Having an appropriate setting in `params.toml` would be an easy solution:

```toml
mastodon = "@stdevel@chaos.social"
```

**Comment by BobPusateri** [comment]
Seconding this request. Mastodon support would be great!

**Comment by onweru** [comment]
@stdevel, @BobPusateri

Curious, how would you like this knob i.e `mastodon = "@stdevel@chaos.social"` would be linked to the UI? Or is that not even necessary? 😃 

Typically, the twitter one, we use it for opengraph purposes.

Also, mastodon icon support was added via #404.

**Comment by stdevel** [comment]
Hi @onweru,
oh great - thanks for pointing out to #404 - didn't know that this already exists.

I just wanted to have a Mastodon icon instead of the Twitter one in the navigation. Updating the thema and using the following lines in `config/_default/menus/menu.$lang.toml` did the trick:

```toml
[[social]]
  name = "mastodon"
  weight = 2
  url = "https://chaos.social/@stdevel/"
```

![image](https://user-images.githubusercontent.com/5862725/216766354-146ee0ab-3ba2-44ba-b6e7-b8449bb120da.png)

Thanks for the support!

**Comment by onweru** [comment]
You're welcome @stdevel. Would you be interested in reviewing #420?
