### ISSUE TITLE
[Bug] Path to thumbnail images incorrect on second and higher page

### ISSUE THREAD

**Issue by Cyb3r-Jak3** [chipzoller/hugo-clarity#427]
### I confirm:

- [X] I am running the [extended version of Hugo version 0.91.0 or above](https://github.com/chipzoller/hugo-clarity/blob/master/README.md#prerequisites) to build my site.
- [X] I have read the [Hugo Clarity theme documentation](https://github.com/chipzoller/hugo-clarity/blob/master/README.md).
- [X] I have used the [example site's config files](https://github.com/chipzoller/hugo-clarity/tree/master/exampleSite/config/_default) as reference.
- [X] I have reviewed [other issues in this repository](https://github.com/chipzoller/hugo-clarity/issues) and mine is not recorded.

### Hugo version

hugo v0.109.0-47b12b83e636224e5e601813ff3e6790c191e371+extended windows/amd64 BuildDate=2022-12-23T10:38:11Z VendorInfo=gohugoio

### Where is this bug showing up?

In the browser: Hugo builds the site, but something doesn't look right.

### Operating system

Windows 10

### Current behavior

When you have posts that go on to a second page, then the thumbnails images all 404.

An example URL is `http://localhost:1313/page/2/images/<folder>/image.png` whereas on the first page the thumbnail images are linked to `http://localhost:1313/images/<folder>/image.png`

### Expected behavior

All images that are loaded from the second page and higher still use the page of `/images` rather than `/<page number>/images`

### Steps to reproduce

Create a project that has at least two pages of posts with thumbnails and go to the second page and there are no thumbnails.

### Related code

My guess is that is comes from this partial
https://github.com/chipzoller/hugo-clarity/blob/master/layouts/partials/figure.html

```html
    {{/* Render image and attributes. */}}
    <img
      loading="lazy"
      decoding="async"
      alt="{{ htmlEscape $alt }}"
      {{ with $image }}
        class="{{ $classes }} image_processed"
        width="{{ .Width }}"
        height="{{ .Height }}"
        src="{{ .RelPermalink }}"
      {{ else }}
        class="{{ $classes }} image_unprocessed"
        src="{{ $fileWeb }}"
      {{ end }}
      {{ with $cap }}
        title="{{ safeHTML $cap }}"
      {{ end }}
    />
```

### Preferred solution

Maybe have the images link be src from absolute?

### Other information

Similar to https://github.com/chipzoller/hugo-clarity/issues/337

**Comment by albersonmiranda** [comment]
Also happens with internationalization. When changing from default to second language, all thumbs are 404. Ex.: https://datamares.netlify.app/
