### ISSUE TITLE
Twitter Share Link doesn't work by default.

### ISSUE THREAD

**Issue by tbraeutigam** [chipzoller/hugo-clarity#43]
**I have checked all the prerequisites below and I'm yet experiencing a problem**

- [x] Read the README.md
- [x] Have the extended version of Hugo installed
- [x] Used the exampleSite's config.toml as a reference

**Describe the bug**

Twitter Share Link doesn't work by default.

To make it work I edited the `layouts/partials/share.html` and added `| urlize` behind the `.Permalink` entries.

**Comment by chipzoller** [comment]
At last look (and on my site using this theme) the Twitter share link worked just fine. @onweru can you confirm?

**Comment by onweru** [comment]
It works in all cases except if you're not already logged onto twitter. I will confirm that quirk again and proceed accordingly.

**Comment by chipzoller** [comment]
Was this confirmed, or should we drop? It seems like a reasonable prereq that a user should be authd to Twitter to enable that functionality.

**Comment by onweru** [comment]
We should drop this one.

**Comment by chipzoller** [comment]
Closed.
