### ISSUE TITLE
Suggestion: Use Copyright Setting from config.toml for footer by default

### ISSUE THREAD

**Issue by tbraeutigam** [chipzoller/hugo-clarity#44]
As the title states I think it might be good to user `{{ .Site.Copyright }}` for the footer by default.

As a newbie to hugo I had to take out the trusted `grep -ri` hammer to find where the copyright notice is defined in the theme.

**Comment by chipzoller** [comment]
@onweru to weigh in here.

**Comment by onweru** [comment]
I think we should leave this one as is. Why?

The copyright section consists of  `current year`(generated automatically), `site name`(defined in config) & all the other text which [was covered under i18n](https://github.com/chipzoller/hugo-clarity/blob/6bbd50f5ae9bd5a3c24a67c653a876b43ad78553/i18n/en.toml#L4-L8) through #39
