### ISSUE TITLE
[Bug] The Webpage DOES NOT Function Properly After Being Deployed to GitHub Pages

### ISSUE THREAD

**Issue by jackgdn** [chipzoller/hugo-clarity#472]
### I confirm:

- [X] I am running the [extended version of Hugo version 0.91.0 or above](https://github.com/chipzoller/hugo-clarity/blob/master/README.md#prerequisites) to build my site.
- [X] I have read the [Hugo Clarity theme documentation](https://github.com/chipzoller/hugo-clarity/blob/master/README.md).
- [X] I have used the [example site's config files](https://github.com/chipzoller/hugo-clarity/tree/master/exampleSite/config/_default) as reference.
- [X] I have reviewed [other issues in this repository](https://github.com/chipzoller/hugo-clarity/issues) and mine is not recorded.

### Hugo version

v0.130.0

### Where is this bug showing up?

In the browser: Hugo builds the site, but something doesn't look right.

### Operating system

Windows 11

### Browser (if applicable)

Edge, Chrome

### Current behavior

![yzpd8-1hdaj](https://github.com/user-attachments/assets/f9ed37f3-b540-4245-852b-fbfa3e9d7ffa)
![su4dv-nkkk4](https://github.com/user-attachments/assets/a73a97d4-0434-41e2-914b-abc5849764b4)
![76cmy-m2sue](https://github.com/user-attachments/assets/fd2a852d-2dba-425c-a777-1f35aa0e693f)
![kut2k-bqtjq](https://github.com/user-attachments/assets/4b650b7e-75a0-4469-895b-433a5a4ea9cb)

After deploying to GitHub Pages, these components are not functioning properly, but they work fine when I preview using `hugo server` command locally.

### Expected behavior

These components should be able to work properly.

### Steps to reproduce

Set up several submenus, enable search.

**Comment by barefootstache** [comment]
This suggests that the JavaScript resources aren't being loaded in correctly. Make sure that the `baseURL` is set to GitHub pages URL and ends with a `/`.

Alternately one can try to debug the issue by inspecting if the various files are reachable from the Developer's Tools in the browser.
