### ISSUE TITLE
For me the Author/Intro is missing from the homepage. i see it on posts and other pages.

### ISSUE THREAD

**Issue by dstamen** [chipzoller/hugo-clarity#5]
https://inspiring-jang-56bfc9.netlify.app/ example.

**Comment by chipzoller** [comment]
Can you provide more details on this issue? Did you try with the exampleSite and found the same thing?

**Comment by dstamen** [comment]
![image](https://user-images.githubusercontent.com/11834898/88809630-5b8ad400-d182-11ea-9e37-73e881b2b22b.png)

top right the author info is missing....

**Comment by dstamen** [comment]
when you go to any other page its there... 
![image](https://user-images.githubusercontent.com/11834898/88809713-6cd3e080-d182-11ea-89e0-fc91344c8663.png)

**Comment by dstamen** [comment]
not sure if this is expected or not.

**Comment by onweru** [comment]
> not sure if this is expected or not.

@dstamen,
 
I will have a look at this man, thanks for highlighting it.

**Comment by dstamen** [comment]
no problem. site the "author" is set in config.toml i would expect it to be
sitewide, however if author is set at the page level then maybe that
updates for the author?

**Comment by onweru** [comment]
I recall why I excluded the author's block from the homepage, and other list pages. I considered a situation where a site has multiple authors. In such a scenario, the author's block on a list page would give a false impression; that all articles are authored by the site owner / main author.

We could add a variable on config file indicating that there's a sole author in a site. Convenient when one isn't expecting a guest author. Yet one cannot always tell what they might do in the future.

**Comment by chipzoller** [comment]
I think that's a valid concern, but I do also think that this is more of a corner case than of the majority. By in large, a user adopting this theme will most likely either be the sole author or the primary author of its content. One possible way to satisfy both concerns is to turn the `author` parameter into an array of strings and then handling that on the side bar with a name on each line. Or just drop that functionality entirely, stay with a single author, and let users fork the theme and hack it to their liking.

**Comment by chipzoller** [comment]
Fixed.
