### ISSUE TITLE
Error with "highlight html" function

### ISSUE THREAD

**Issue by bluelupo** [chipzoller/hugo-clarity#54]
The function {{< highlight html >}} for code blocks in the source file shows an error on my webspace when I move the mouse pointer over a code box (see my webside). It does not matter which browser (e.g. Firefox or Chromium) I use, the error message appears on both browsers.

But if I call this page locally with the built-in webserver of hugo, no error message appears.

The page is available online at:
https://bluelupo.info/post/aktuelle-betaversionen-von-firefox-nutzen/

Here you can see the error.

regards
Michael

**Comment by razonyang** [comment]
Some icons(copy.svg, expand.svg ...) do not exist in https://bluelupo.info/icons/. I guess that is a problem of your web server configuration.

**Comment by onweru** [comment]
nothing to see here.
