### ISSUE TITLE
Coding style

### ISSUE THREAD

**Issue by razonyang** [chipzoller/hugo-clarity#56]
I found that this theme contains different coding styles about HTML element property.

```html
<!--no spaces delimiter-->
<meta property="foo" content="bar" />

<!--with spaces delimiter-->
<meta property = "fizz" content = "buzz" />
```

According to the standard, it doesn't matter. However, it is better to use the same coding style. So which one should be used when making a PR?

References:

- [Using spaces before and after the `=` sign of HTML element attribute](https://stackoverflow.com/questions/3551541/using-spaces-before-and-after-the-sign-of-html-element-attribute)

**Comment by chipzoller** [comment]
I always go for economy, so no spaces delimiter is what I'd use here.
