### ISSUE TITLE
Unable to hide Language selection with site variable

### ISSUE THREAD

**Issue by kevball2** [chipzoller/hugo-clarity#57]
**I have checked all the prerequisites below and I'm yet experiencing a problem**

- [x] Read the README.md
- [x] Have the extended version of Hugo installed
- [x] Used the exampleSite's config.toml as a reference

**Describe the bug**

Setting the isMultiLingual site variable to 0 in the config.toml does not cause the Language selection nav to be hidden (or not rendered). Should this be expected behavior? The nav.html file contains a check if {{ if .Site.IsMultiLingual }}, Should the language navigation be disabled another way? 

**Desktop (please complete the following information):**
 - OS: Windows 10 w/ WSL running Hugo on Ubuntu 20.04
 - Browser: Edge v 87.0.656.0 and 85.0.564.63

**Comment by tcarreira** [comment]
@kevball2 There is no isMultiLingual
Hugo auto-detects multilingual if there is any translation available.

If you delete the [pt] part from `conf/_default/language.toml` and delete the file `conf/_default/menus/menu.pt.toml` (that you  copied from the exampleSite, the translation disappears)

@onweru This should be addressed in the documentation.
What do you think is best:
- have a onliner command line to remove the multilang content from the example is needed?
- only one language @ exampleSite. Get another extraMultilangSite with the extra needed files?
- have another extra config variable to address this?

I would go for the first one, but the last one may be the simplest one for newbies.

**Comment by onweru** [comment]
@tcarreira, let's go with this 👇 
> have a onliner command line to remove the multilang content from the example is needed?

Thanks for your help here.

**Comment by tcarreira** [comment]
#58

**Comment by kevball2** [comment]
@tcarreira  Thanks for the info, just learning Hugo and thought all the site variables could be used to enable/disable features. Appreciate the quick feedback!
