### ISSUE TITLE
If draft = true, it is not rendered. in development mode

### ISSUE THREAD

**Issue by dstamen** [chipzoller/hugo-clarity#6]
draft = true is a valid post configuration.

this is used when writing a post but not having it generated with hugo build process. when draft = true the page is not rendered for preview on localhost:1313

this was tested in examplesite

![image](https://user-images.githubusercontent.com/11834898/89036875-7f2d5600-d30b-11ea-8f09-29bb96be923a.png)

**Comment by chipzoller** [comment]
Not sure I completely follow. TMK, this is expected behavior from Hugo. When `draft = true` the site will not be rendered irrespective of theme. You say "in development mode" so I'm not sure if you're saying there's a switch (which I can't find) which should enable these drafts to build.

**Comment by dstamen** [comment]
Ignore my friday brain...

**Comment by onweru** [comment]
ℹ️  you can always run `hugo server --buildDrafts` or `hugo server -D` if you want to render drafts on localhost. [See options](https://gohugo.io/commands/hugo_server/#options)
