### ISSUE TITLE
Add MailChimp Signup Form configuration

### ISSUE THREAD

**Issue by gleaneo** [chipzoller/hugo-clarity#60]
Dear author,

Thank you so much for this amazing theme. It would be great if you please provide the setting on config file for adding the the link of Sign up form provided by mail-chimp.

The requested setting is provided by another [hugo theme](https://github.com/felicianotech/hugo-theme-lean-launch-page#mailchimp).

**Comment by chipzoller** [comment]
Our theme is primarily targeted at bloggers writing technical content whereas MailChimp sign-up forms are more commonly used on product pages. @onweru what are your thoughts here?

**Comment by onweru** [comment]
@chipzoller,
> Our theme is primarily targeted at bloggers writing technical content whereas MailChimp sign-up forms are more commonly used on product pages. @onweru what are your thoughts here?

I agree. 

@gleaneo, 
> It would be great if you please provide the setting on config file for adding the the link of Sign up form provided by mail-chimp.

To add that sort of functionality, you can use hooks added by @razonyang in #50. It's [documented  here](https://github.com/chipzoller/hugo-clarity#hooks)
