### ISSUE TITLE
Disqus shortname not enabling the inclusion

### ISSUE THREAD

**Issue by shawnmasters** [chipzoller/hugo-clarity#61]
I've added the following shortcode to my config.toml

# Disqus shortname
disqusShortname = "anticryptography"

and the generation step does not seem to be picking it up.  There is no reference in any of the posts to Disqus.  Does this require more than the shortname?

**Comment by razonyang** [comment]
There are several reasons cause this:
1. `disqusShortname`  should be placed in root level in config(same as `baseurl`, `title`). Put it under`params` will not work.
1. Have you disabled comment globally by setting `comment = false` in config?
1. Have you disabled comment in particular post by setting `comment = false` in post's front matter?

**Comment by shawnmasters** [comment]
Ah, I had it under params.  Good to know.  Is this documented somewhere?

**Comment by razonyang** [comment]
> Is this documented somewhere?

Not yet. I create a PR #62 for it.
