### ISSUE TITLE
Site doesn't build

### ISSUE THREAD

**Issue by TheJavaGuy** [chipzoller/hugo-clarity#69]
**I have checked all the prerequisites below and I'm yet experiencing a problem**

- [x] Read the README.md
- [x] Have the extended version of Hugo installed
- [x] Used the exampleSite's config.toml as a reference

**Describe the bug**

I tried to install this theme by following this procedure:
```bash
hugo new site mysite
cd mysite
git init
git submodule add https://github.com/chipzoller/hugo-clarity themes/hugo-clarity
cp -a themes/hugo-clarity/exampleSite/* .
hugo server
```
but immediately after executing `hugo server` I got the following error message:
```
$ hugo server
Start building sites …
ERROR 2020/10/23 23:52:10 Failed to get JSON resource "https://api.instagram.com/oembed/?url=https://www.instagram.com/p/BGvuInzyFAe/&amp;maxwidth=640&amp;omitscript=true": Failed to retrieve remote file: Bad Request
Built in 568 ms
Error: Error building site: logged 1 error(s)
```

**Desktop (please complete the following information):**
 - OS: Windows 10 Version 10.0.19041.572
 - hugo version: `Hugo Static Site Generator v0.76.2/extended windows/amd64 BuildDate: unknown`
 - hugo-clarity: commit https://github.com/chipzoller/hugo-clarity/commit/f59e0e1e8f811d7bed5734c333f0682a3fad975a

**Comment by KTM888** [comment]
I have the same exact issue, does anyone know how to fix?

**Comment by chipzoller** [comment]
Instagram have deprecated their existing oEmbed endpoint as outlined in [this post](https://developers.facebook.com/docs/instagram/oembed). We will need to adjust the theme to pull from the correct endpoints from now on.

**Comment by onweru** [comment]
@chipzoller 
> Instagram have deprecated their existing oEmbed endpoint as outlined in this post. We will need to adjust the theme to pull from the correct endpoints from now on.

The error was being caused by https://gohugo.io/content-management/shortcodes/#instagram. 8da522e should suffice until the shortcode is fixed.

@TheJavaGuy, @KTM888, you should be able to proceed now.

**Comment by TheJavaGuy** [comment]
Thank you @onweru and @chipzoller , you guys rock!
