### ISSUE TITLE
How to override css and js with additional files?

### ISSUE THREAD

**Issue by bilal-fazlani** [chipzoller/hugo-clarity#7]

**Comment by onweru** [comment]
@bilal-fazlani, I will add files for that purpose.

**Comment by bilal-fazlani** [comment]
Thanks @onweru !

**Comment by bilal-fazlani** [comment]
I have added a pull request for adding class names to images here #9 .
We will be able to add styles to these classes once there is ability to add custom css/js files

**Comment by bilal-fazlani** [comment]
Updated the PR to add this support this functionality as well
