### ISSUE TITLE
Thumbnail image path for page bundles.

### ISSUE THREAD

**Issue by rugginic** [chipzoller/hugo-clarity#72]
Hello and thank you for this amazing theme.
I'd like to ask 3 questions I couldn't find an answer for in the documentation:
1. I'm trying to keep posts and their resources (images, attachments, ecc) within the content folder, leveraging page bundles. One thing I noticed, the thumbnail image path apparently always points to the static folder. I couldn't manage to keep all the post's content within the same post folder "/content/post/2020-10-10-post-title-folder/"
is there a way to do so? or am I missing something? what would be the best practice in terms of content management?

2. what would be the best way to customise the theme (color scheme, fonts, ecc)

3. I noticed the theme does not have "reading time" for articles and internal search option to search through the posts. I wonder a scenario where I have hundreds of posts in my blog and and I want to search for a word or a phrase. How would one achieve this?

Thanks and Regards,
Nicola

**Comment by chipzoller** [comment]
Hello, Nicola. I can handle the third question while the other two would be better answered by @onweru. We currently have not implemented a search function, however this is planned in the 2.0 milestone via a custom implementation. The "reading time" function you mentioned is a separate piece of functionality if you're asking about blogs that state something like "estimated 5 minutes to read" up front. This isn't something that a search function would solve, however.

**Comment by rugginic** [comment]
Hello Chip! Thanks for coming back to me! You are right,  In fact my 3rd question was a kind of "feature request" for 2 separate features:
1. Reading time as many other themes already have. Exactly what you are referring to: "estimated reading time" nice to have for a casual reader who has 5 spare minutes and might not start reading an article that takes an average of 30 minutes to read (or vice versa!)
2. The second is for implementing search through articles. I read that it is planned for v2.0 release and also here someone has already implemented a custom search page, that could do for me while waiting for the official release!

Just out of curiosity, what is your approach in terms of page resources? When you publish a new post that has a bunch of screenshots, thumbnail, featured image and possibly search image, do you use the "static folder" for images and other content? and "content folder" only for the MDs?

Thanks,
Nicola

**Comment by chipzoller** [comment]
The first feature is something we aren't planning to implement at this time, but of course that's subject to change especially if there's more interest. The second feature, as I said, will get implemented in 2.0. That will probably be a next year target.

For page resources, the convention in Hugo is to separate static files from text content because images, icons, etc don't get rendered by Hugo while text (in the form of MD) does. So for my own blog, I create a dir for the year-month followed by a year for the post title. I do this for both content and static sides. Separating that content also helps in some CI/CD processes where changes occur in only one directory while leaving images be.

**Comment by onweru** [comment]
@rugginic,

> what would be the best way to customise the theme (color scheme, fonts, ecc)

I believe that is [covered, to a good degree, in the readme](https://github.com/chipzoller/hugo-clarity#custom-css-and-js)

> do you use the "static folder" for images and other content? and "content folder" only for the MDs?

That's exactly right.

> I'm trying to keep posts and their resources (images, attachments, ecc) within the content folder, leveraging page bundles.

I'm familiar with the concept of page bundles, but I have so far ignored them to an obvious fault. Nonetheless for a good reason; I find media management [on __forestry cms__ (most SSG cms) painful when Hugo page resources are applied](https://forestry.io/blog/how-to-use-hugo-s-image-processing-with-forestry/). I'll give this some thought, and if the theme can support page bundles simultaneously, I'll add support. Thanks for raising this.

**Comment by rugginic** [comment]
@onweru Thank you,
> I believe that is covered, to a good degree, in the readme
yes, you are right. is it covered in the readme, and my apologies if I'm asking silly questions, I guess this is more related to git and workflow instead of this theme: I wanted to change the background color and, following the instruction I modifies [_variables.sass](https://github.com/chipzoller/hugo-clarity/blob/master/assets/sass/_variables.sass), but now git complains about untracked changes for the submodule.
I know I could just clone the repository instead of adding the submodule, but in this way, wouldn't I miss the chance to update the theme in the future when a new release is available?
>  I find media management on forestry cms (most SSG cms) painful when Hugo page resources are applied.
Sorry, I'm not sure I understand how forestry is related. For my understanding, image processing was introduced in hugo for the purpose to help manage images on page bundles, right? That's why image processing only applies to images within the "content" folder, as per Hugo guidelines on [Content Management](https://gohugo.io/content-management/organization/).
> For page resources, the convention in Hugo is to separate static files from text content
I'm confused, Isn't it contradicting the concept of [Page Bundles](https://gohugo.io/content-management/page-bundles/)?

**Comment by chipzoller** [comment]
Yes, that's the concept of Page Bundles, but they're a (fairly) new concept to Hugo. Prior to Page Bundles, the convention was that non-rendered files (typically images) should be defined in `/static` which is what we're currently doing. Bundles are certainly something I'd like to see, but that's just going to take a little time.

**Comment by rugginic** [comment]
@onweru 

> Pro Tip: You can change the theme colors via the this variable's SASS file

How do one overrides the _variables.sass or creates a custom .sass outside the them folder? I'm quite happy with changing $bg and $theme colors and I think I tried almost everything but I can't manage to change those settinngs leaving the theme's folder untouched. Can you please help?

**Comment by rugginic** [comment]
@onweru Thanks a lot!
I maneged to override the colors creating /assets/sass/_override.sass !!
Just a heads up:

> // we recommend not editing this file directly. Instead, create an `assets/sass/override.sass` file at the root level of your site.

In my case it didn't work without the "_" underscore. The file has to be renamed _override.sass

**Comment by onweru** [comment]
@rugginic, thanks for catching that.
