### ISSUE TITLE
consider renaming icons/ directory, as it clashes with some apache default configs 

### ISSUE THREAD

**Issue by knurd** [chipzoller/hugo-clarity#74]
I'm getting 404 for everything in the icons/ directory after uploading it to my shared webspace. Turns out there is a name clash, as a icons/ directory in the root has a special meaning in some apache default confits. See https://electrictoolbox.com/apache-icons-directory/ or https://www.hosteurope.de/faq/webhosting/hochladen-von-webinhalten-ftp/verzeichnisnamen-mit-besonderer-funktion/ (german, sorry) for details – or google for something like ' "icons" directory webserver 404 '. 

Hence please consider renaming the static/icons/ to something else.

**Comment by chipzoller** [comment]
Best we can probably do here is provide the *option* to use a different name, but the default of `icons` is quite standard in the vast majority of cases. @onweru do we want to support this?

**Comment by onweru** [comment]
@chipzoller 

> Best we can probably do here is provide the _option_ to use a different name, but the default of `icons` is quite standard in the vast majority of cases. @onweru do we want to support this?

I attempted accomodating this by implementing the tip from https://electrictoolbox.com/apache-icons-directory/ (suggested by @knurd). It introduces a breaking change. At this point, I would suggest we keep this open for future consideration.

@knurd,

As a temporary measure, I would recommend editing finding where __icons/__ paths is used and modifying accordingly:
`grep -w -r -o -n "icons" .`

**Comment by onweru** [comment]
@knurd, here https://github.com/chipzoller/hugo-clarity/blob/a685f840b5a744ab6f22a6eb9ff16e8bc7fdae00/exampleSite/config/_default/params.toml#L82-L83
