### ISSUE TITLE
Posts with future `date` in frontmatter invalid

### ISSUE THREAD

**Issue by chipzoller** [chipzoller/hugo-clarity#76]
If setting the `date` key in the post's frontmatter to a day in the future, Hugo won't render the page. Is this something we can allow? Main use case I can forsee is when someone wants to use a CD platform to publish a post on a given timer and flip `draft` from `true` to `false` simultaneously.

**Comment by onweru** [comment]
For sure, there's a [hugo build flag for that sort of thing](https://gohugo.io/getting-started/usage/#draft-future-and-expired-content)

**Comment by chipzoller** [comment]
Did not know about that flag! Thanks, @onweru. Closed.
