### ISSUE TITLE
Twitter large summary card support

### ISSUE THREAD

**Issue by bilal-fazlani** [chipzoller/hugo-clarity#8]
https://developer.twitter.com/en/docs/tweets/optimize-with-cards/overview/summary-card-with-large-image

It would be great to support this 

![image](https://user-images.githubusercontent.com/3396271/89168701-dbf27000-d59a-11ea-98c1-6f7233ba0da3.png)

Right now, they come out like this:

![image](https://user-images.githubusercontent.com/3396271/89168832-0c3a0e80-d59b-11ea-9a43-64ea3618b9ef.png)

**Comment by onweru** [comment]
@bilal-fazlani,

I agree; I will make it configurable via the config. Thanks for the feedback

**Comment by chipzoller** [comment]
Will update readme soon with this param.

**Comment by bilal-fazlani** [comment]
thank you for closing all the issues quickly! great theme!
