### ISSUE TITLE
elems.forEach is not a function at toggleLineNumbers

### ISSUE THREAD

**Issue by Stals** [chipzoller/hugo-clarity#84]
**I have checked all the prerequisites below and I'm yet experiencing a problem**

- [x] Read the README.md
- [x] Have the extended version of Hugo installed
- [x] Used the exampleSite's config.toml as a reference

**Describe the bug**

When I open the page that contains some code, for example like this:
```
{{< highlight "C#" "linenos=table" >}}
var sequence = DOTween.Sequence();
sequence.Append(transform.DOMoveY(transform.position.y - 20, 1f).SetEase(Ease.OutBounce));
sequence.Join(transform.DOMoveX(transform.position.x + 25, 1f));
{{< /highlight >}}
```

The page breaks with an error
```
bundle.min.4e7574e16d1a39ca31d50b7222cc3797c351be47295deaf1e34a33de8af77978f86a30143f855ea2241d3b1e6cf05912bd2f70570aab3db384c2a1a5ca057cc1.js:38 Uncaught TypeError: elems.forEach is not a function
    at toggleLineNumbers (bundle.min.4e7574e16d1a39ca31d50b7222cc3797c351be47295deaf1e34a33de8af77978f86a30143f855ea2241d3b1e6cf05912bd2f70570aab3db384c2a1a5ca057cc1.js:38)
    at disableCodeLineNumbers (bundle.min.4e7574e16d1a39ca31d50b7222cc3797c351be47295deaf1e34a33de8af77978f86a30143f855ea2241d3b1e6cf05912bd2f70570aab3db384c2a1a5ca057cc1.js:43)
    at bundle.min.4e7574e16d1a39ca31d50b7222cc3797c351be47295deaf1e34a33de8af77978f86a30143f855ea2241d3b1e6cf05912bd2f70570aab3db384c2a1a5ca057cc1.js:44
    at Array.forEach (<anonymous>)
    at codeActions (bundle.min.4e7574e16d1a39ca31d50b7222cc3797c351be47295deaf1e34a33de8af77978f86a30143f855ea2241d3b1e6cf05912bd2f70570aab3db384c2a1a5ca057cc1.js:44)
    at bundle.min.4e7574e16d1a39ca31d50b7222cc3797c351be47295deaf1e34a33de8af77978f86a30143f855ea2241d3b1e6cf05912bd2f70570aab3db384c2a1a5ca057cc1.js:47
```

If I set "codeLineNumbers = true" in config.toml the error doesn't happen, but then if I try to press the buttons near the code, the same error happens with a different stacktrace 

Tried updating, tested on 7dc4781a (the latest commit in master at the moment) still happens.

**Desktop (please complete the following information):**
 - OS: MacOS 10.14.6
 - Browser: Google Chrome 86.0.4240.111 (Official Build) (x86_64)
 - Hugo: v0.76.5-60F0725B/extended

**Comment by Stals** [comment]
Seems to be caused by the "linenos=table" part,
I've also missed this line in the config file

`lineNumbersInTable = false # toggling this on (i.e to true) or deleting this line will break the code blocks functionality. Will`
Which seems to be incomplete

**Comment by onweru** [comment]
> Seems to be caused by the "linenos=table" part,
> I've also missed this line in the config file
> 
> `lineNumbersInTable = false # toggling this on (i.e to true) or deleting this line will break the code blocks functionality. Will`
> Which seems to be incomplete

@Stals, glad you found the comment. Support for `lineNumbersInTable = true` will come later.

> ... At this point, [we've limited our scope in fact](https://github.com/chipzoller/hugo-clarity/blob/b67849d1ca101457d245fef9e79a9325a8b52468/exampleSite/config.toml#L40). Our next step would be to support all functionality when this condition -> `lineNumbersInTable = true` is set. 
...

_Originally posted by @onweru in https://github.com/chipzoller/hugo-clarity/issues/75#issuecomment-723733494_
