### ISSUE TITLE
Image figure caption disappears after refreshing the page

### ISSUE THREAD

**Issue by rugginic** [chipzoller/hugo-clarity#93]
Hi All,

I noticed that the figure [caption disappears](https://themes.gohugo.io/hugo-clarity/#image-figure-captions) after refreshing the page.

I noticed it on my site, but then I tried also @chipzoller site. This is an example from https://neonmirrors.net/post/2020-05/cicd-for-hugo-on-aws/

This is the caption:
![caption](https://user-images.githubusercontent.com/68188977/99788707-64c8f380-2b19-11eb-949a-8af58ecff1a4.png)

And this is after refreshing the page:
![no-caption](https://user-images.githubusercontent.com/68188977/99788711-6692b700-2b19-11eb-8fc5-dc344c3496a8.png)

Using Chrome and Chromium, tried from my Android phone as well.

**Comment by chipzoller** [comment]
Yes, I'm seeing the same thing on Brave on desktop, but not on Firefox. On Firefox, refreshing can sometimes double print the image captions, which we thought was just Firefox being...Firefox. Will need to investigate here.

**Comment by onweru** [comment]
@chipzoller, @rugginic 

Let me know if this is fixed.

**Comment by chipzoller** [comment]
Per earlier discussion, issues still persist when changes are pushed to a live site where there is loading latency greater than what is seen when running Hugo locally.

**Comment by rugginic** [comment]
@onweru, @chipzoller 
Apologies for late reply.
I've just checked out the latest and it appears that is fixed for me. Ma pages are hosted at gitlab.

Thank you Guys, great job!

**Comment by chipzoller** [comment]
Appears fixed as well. Closing.
