### ISSUE TITLE
Code block expansion stops at empty line

### ISSUE THREAD

**Issue by chipzoller** [chipzoller/hugo-clarity#94]
**I have checked all the prerequisites below and I'm yet experiencing a problem**

- [x] Read the README.md
- [x] Have the extended version of Hugo installed
- [x] Used the exampleSite's config.toml as a reference

**Describe the bug**

When having a code block which is, for example, 30 lines long and in which there is a blank line at 21, when setting the default number of lines to show at 30 the code block will still be collapsed showing up to that blank line.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Firefox 82

**Comment by chipzoller** [comment]
I can't recall, is this something you were able to reproduce, @onweru ?

**Comment by onweru** [comment]
@chipzoller, I was able to reproduce it. It was an edge case though. That’s it only occurred when a specific condition occurred.

**Comment by chipzoller** [comment]
Can this be remediated in the current version track?

**Comment by onweru** [comment]
Once I give it the attention it needs, yes.

**Comment by onweru** [comment]
@chipzoller, can you reproduce this again. Following your initial description, I was unable to reproduce it.

**Comment by chipzoller** [comment]
Will check.

**Comment by chipzoller** [comment]
Tried this again and can't reproduce. Closing until further notice.
